CHANGES
holidays.py
tests.py

This adds New Zealand as another holiday country class. Includes provincial anniversary days.

Added holidays for New Zealand

---

holidays.py
tests.py

This adds all German holidays for all provinces since it's unification in 1990.
There are some special edge cases since some province specific have complicated
sub-rules but those are document in the docstring of the class.

Adds German holidays

---

holidays.py
tests.py

On second thought, I think it would be more correct if I remove the holidays which are not officially real holidays: Grundlovsdag ("Constitution Day"), Juleaftensdag ("Christmas Eve's Day"), and Nytårsaftensdag ("New Year's Eve's Day"). On these days most stores and offices are closing but again, they are not real holidays.

Add Danish holidays and tests

---

README.rst
holidays.py
tests.py

TAR holidays are published by European Central Bank.
Naming EU might be ambiguous.

renamed EU calendar to ECB 

---

setup.py

This allows the package to be installed in non-unicode locales.

Specify encoding when parsing for version in holidays.py

---

holidays.py
tests.py

Liberation Day ("Bevrijdingsdag") is an official celebratory day in the Netherlands but not a holiday where *everyone* is free from work, although a lot of people (especially those working for the government) do not have to work once every 5 years (`year % 5`; the current logic). Since this does not apply to everyone, this day should be removed from the Dutch holidays.
See #38 for more details.
@j92 Since you implemented the Dutch holidays (Bedankt daarvoor trouwens 😉), could you review this PR?

CHANGE - Removes Liberation Day NL after 2000 (#38)

---

README.rst
holidays.py
tests.py

In Norway, all Sundays are considered holidays. I can see that a lot of users would want Sunday to not be considered a holiday, so I added a parameter to Norway.\_\_init\_\_ (*include_sundays*) to allow them to control whether they should be considered a holiday or not. Currently, it defaults to True.
I've also used asserts in the code to check that the days of easter always fall on the same weekdays. I believe this is good practice, as something is horribly wrong (for example in dateutils.easter) if this is not true.

Add Norwegian holidays

---

README.rst
holidays.py
tests.py

Slovakia is official country since 1.1.1993 when Czechoslovakia split into Czechia (Czech republic and Slovakia (Slovak republic). Since then, two official holidays were added in 1997 and 2001.
Sources:
https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/1993/241/20160101.html (legislation)
https://sk.wikipedia.org/wiki/Sviatok (wikipedia)
With this PR I grant all required licenses to this code.

Add Slovak holidays

---

README.rst
holidays.py
tests.py

Code cleanup:
* Remove redundant parentheses
* Simplify chained comparison
* Make variables lowercase
* Fix typos
List/dict upgrades:
* Rewrite unnecessary generator as a dict comprehension
* Rewrite unnecessary list call as literal
* Replace unnecessary list comprehension - 'sum' can take a generator
Tests:
* Update asserts to give descriptive feedback instead of only using `assertTrue`/`assertFalse`
* Fix some broken tests: `"name"` in `assertTrue(holiday, "name")` is just a message shown on failure, and will never fail. These should really be `assertEqual(holiday, "name")` which can fail.

Various inspection fixes

---

holidays.py
tests.py

Since 2018 these provinces in Germany also have Reformationstag.
- HB (Bremen)
- HH (Hamburg)
- NI (Niedersachsen)
- SH (Schleswig-Holstein)
See also https://www.schulferien.org/deutschland/feiertage/reformationstag/ for reference.

additional German provinces got "Reformationstag"

---

holidays.py

This reverts commit 22e404c2d6662a012ecec64170d1c2d5545b2e10 because the new
holidays were already introduced in f2814a79b7ab7688763a711cf8274155d4857675.

Revert 'additional German provinces got "Reformationstag"'. Added holidays twice.

---

holidays.py
tests.py

In #110 a problem with the German public Easter and Pentecost holidays was introduced.

fix German holidays

---

holidays.py
tests.py

Added support for Luxembourgish holidays.
More info can be found here: https://en.wikipedia.org/wiki/Public_holidays_in_Luxembourg
This list also includes May 9th, which will be a public holiday starting in 2019 (although the legislation has yet to be updated).
Edit: Please excuse the many fixes, this is my first PR ;-)

Support for Luxembourgish holidays

---

README.rst
holidays.py
tests.py

RE #113 Allow users to get the dates for which any holiday falls within a date range. Implemented using slice notation; users simply give [start, stop, step], where step is optional. Sample usage:
```
>>> holidays.US()[date(2013, 12, 31): date(2014, 1, 2)]
[datetime.date(2014, 1, 1)]
>>> holidays.US()[date(2014, 1, 1): date(2013, 12, 24)]
[datetime.date(2014, 1, 1), datetime.date(2013, 12, 25)]
>>> holidays.CA()[date(2013, 12, 25): date(2014, 1, 2): 3]
[datetime.date(2013, 12, 25)]
```
Uses the existing `__keytransform__` functionality so users may use dates, datetimes, strings, etc. Step field may be given as a positive or negative integer or timedelta (only days interpreted), or use default step of one day.
Infinite sequences, such as `[date(2014, 1, 1):]` are not implemented and are …

Holidays in date range

---

holidays.py
tests.py

Senate of Berlin has decided to add this holiday. See https://www.berlin.de/aktuelles/berlin/5652179-958092-nun-auch-offiziell-frauentag-wird-feiert.html

Add international women's day to berlin/germany's holidays

---

holidays.py
tests.py

From 2019 onwards, March 8 will be a national holiday in Berlin/Germany (International Women's Day).
In 2020, May 8 will be a national holiday in Berlin/Germany (75th anniversary of the end of World War 2).

Add 2 holidays to Berlin/Germany

---

holidays.py
tests.py

It should work like this.
You're usually testing against the abbreviated names, e.g. CZ, IT, ... which leaves the test unchanged :-)
I am still having one issue - if I put the semantically correct deprecation warning in the code, it is by default not printed, as Python ignores it (see https://docs.python.org/3.6/library/warnings.html#default-warning-filters ).

Make Czech deprecated, introduce Czechia instead

---

holidays.py
tests.py

Changes in this PR:
- Let `prov` be None by default to get national public holidays (and not the ones from ACT)
- Easter Sunday also in ACT, QLD and VIC
- Queen's Birthday is not a national but a common state public holiday
- NSW has a Bank Holiday on the first Monday in August
- Family & Community Day in ACT was replaced by Reconciliation Day starting 2018

Fixes for Australian public holidays

---

holidays.py
tests.py

* The "Weltkindertag" was resolved as a public holiday in Thuringia (Germany) in early 2019 [1] [2]
* The "Frauentag" was resolved as a public holiday in Berlin (Germany) in mid 2018 [3] [4]
[1] https://www.mdr.de/nachrichten/politik/regional/kindertag-zwanzigster-september-feiertag-thueringen-100.html
[2] http://www.tellerreport.com/news/--landtag--world-children-s-day-is-now-a-public-holiday-in-thuringia-.rytDnSB8V.html
[3] https://www.dw.com/en/berlin-set-to-make-international-womens-day-a-public-holiday/a-46446222
[4] https://www.berlin.de/special/familien/5597854-2864562-frauentag-8-maerz-neuer-feiertag.html

Added new German public holidays

---

holidays.py

Not the first Monday in March, but currently the second Monday in March. Historically the date changes around a bit. Added these in changes back to 1913, the first Canberra Day.

Updated Australia:Canberra Day holiday dates. 

---

holidays.py
tests.py

* Ensure `years` can be passed to the `CountryHoliday` function.
This simplifies programatic generation of years for multiple countries
(i.e. one does not have to call specific country-specfic functions
when one wants to create holidays for multiple years based just on
country strings).
* Add a test that ensure this new functionality works correctly.
Signed-off-by: mr.Shu <mr@shu.io>

update: Allow passing years to CountryHoliday

---

holidays.py

stumbled upon this when trying to use and thought it should be aligned with #186 .
What do you think?

Make Polish deprecated, introduce Poland instead

---

holidays.py
tests.py

This holiday is normally on the first Monday in May, but in 2020
it's being moved to Friday 8th May in order to mark the 75th
anniversary of VE Day.  This is as published on the following
official government webpages for England and Wales, Scotland, and
Northern Ireland:
* https://www.gov.uk/bank-holidays#england-and-wales
* https://www.gov.uk/bank-holidays#scotland
* https://www.gov.uk/bank-holidays#northern-ireland
However, note that Ireland (which also inherits from the
UnitedKingdom class in a not very politically correct manner)
seems to be following the normal 'first Monday in May' rules in
2020 to the best of my knowledge at time of writing:
* https://publicholidays.ie/2020-dates/

Correctly handle United Kingdom "May Day" holiday in 2020.

---

holidays.py

The public holiday "Maria Empfängis" / "Maria Himmelfahrt" is officially written using a german umlaut ä.
Source for Austria: https://www.oesterreich.gv.at/themen/bildung_und_neue_medien/schule/3/Seite.1100108.html
Source for Swizzerland: https://de.wikipedia.org/wiki/Feiertage_in_der_Schweiz

Change Maria to Mariä for AT/CH

---

holidays.py
tests.py

In the last century, Hungary switched its governmental system several
times backed by drastically different ideologies and, of course, it came
with change of officially endorsed holidays, too. I also did my best to
figure out which currently endorsed national holiday had been introduced
in which year.
In the last couple of decades, another trend emerged, the swap days
around official national holidays. Basically, if a holiday falls on
Tuesday or Thursday, that is, only one weekday is between the holiday
and the closest weekend, that weekday is a day off work usually. These
days are also captured if observed is True.
So far so good but these rest days come at cost. Saturday within at most
2 week distance of that weekday will be a working day. I do not know how
to represent those days in …

Hungarian calendar is flavoured by bit of history & swapped days off.

---

holidays.py

If year < 1990 this code is never executed anyways
because earlier in this function there's:
if year <= 1989:
return

remove redundant year check

---

holidays.py
tests.py

The docstring states:
This class doesn't return any holidays before 1990-10-03.
So we can return the holiday on 1990-10-03 itself.

return national holiday already for 1990

---

holidays.py
tests.py

The docstring clearly states:
This class doesn't return any holidays before
1990-10-03.
1990-06-17 is before 1990-10-03 and was no holiday in parts
of todays's Germany.
Source: https://de.wikipedia.org/wiki/Tag_der_Deutschen_Einheit#Bundesrepublik_Deutschland

Don't return holidays before country exists

---

holidays.py

At the moment `"2019-10-31" in holidays.DE()` returns `True` which leads to confusion as we expected the library to only check for nationwide holidays when not passing a specific province.
The PR makes sure we only check for nationwide holidays in this case.

Only return nationwide holidays for Germany when no province is passed explicitly

---

holidays.py
tests.py

We are using `holidays` in [Home Assistant](https://www.home-assistant.io/) to allow the users to get information about workdays. We maintain a copy of the supported countries to have configuration validation. With the proposed addition (`list_supported_countries()`) it would be possible to get the supported countries from the module itself. This would help us to avoid issue like  https://github.com/home-assistant/home-assistant/issues/28977.
```bash
$ python3
Python 3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import holidays
>>> holidays.list_supported_countries()
['AR', 'AT', 'AU', 'AW', 'Argentina', 'Aruba', 'Australia', 'Austria', 'BE', 'BG', 'BR', 'BY', 'Belarus', …
```

Add method to list all supported countries

---

holidays.py

Hello! Wonderful library, thanks so much for maintaining it! I found that the **Czech** class (although deprecated) was not backwards compatible. It's definitely not a huge issue, but I was forced to develop a workaround for this in my use-case, so I figured I'd create a PR for it. 
Deprecated Czech class was not backwards compatible by failing to pass `**kwargs` through to parent's `__init__`.

Deprecated Czech class was not backwards compatible.

---

tests.py

A missing blank line in tests.py, the build was failed and got E305 expected 2 blank lines after class or function definition.
All tests passed. Coverage 100%

Fix E305 expected 2 blank lines missing - Coverage Tests

---

holidays.py
tests.py

Hurray!
From 2020 the second of January is the new national holiday in Belarus (New Year) according to the [presidential decree #464](http://president.gov.by/uploads/documents/2019/464uk.pdf):
"New Year - 1 **and 2 of January**"

Belarus (BY): add January, 2nd as a national holiday

---

README.rst
holidays/countries/__init__.py
holidays/countries/egypt.py
tests.py

The PR is meant to add support for Egypt.
Key notes:
* Weekend Days are (Friday, Saturday)
* The module adds vanilla support for Egypt Holidays 
* Support for shifting holidays due to weekends are there but not active since there is no formal rule.

Adding Vanilla Support for Egypt

---

holidays.py

The 'name' variable has not been set to Alaska Day resulting in an incorrect name when the observed day logic is executed. The name is incorrectly set to Independence Day under this condition.

Fix Alaska Day bug

---

README.rst

Found a minor typo in the README while using this great library. 🎉 
Thanks for the work put into this by the way.

Resolve HolidaysBase() typo for HolidayBase() in README.

---

README.rst

Add an example for listing all holidays in a range of multiple years.

Add example for listing holidays of multiple years

---

holidays/countries/netherlands.py

Adds Good Friday to the Dutch holidays. 
Good friday is always the first friday prior to easter.

Updates netherlands.py

---

holidays/countries/korea.py
holidays/countries/vietnam.py
tests.py

It is a supplement for PR #306  
Not only korea.py, but vietnam.py uses 'korean_lunar_calendar'. So this issue must deal with korea.py and vietnam.py together.

Fix AttributeError: 'Korea' and 'Vietnam' object has no attribute 'korean_cal'

---

holidays/countries/switzerland.py
tests.py

A couple of fixes for the Geneva canton in Switzerland:
* "Berchtoldstag" is not a holiday in Geneva.
* "L'Escalade", while a celebration in Geneva, is not a holiday.
* Unlike the rest of Switzerland where the Federal fast is a holiday (3rd Sunday in September), Geneva has the Genevan fast on the Thursday following the 1st Sunday in September.
References:
https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland
https://www.ge.ch/legislation/rsg/f/s/rsg_j1_45.html (in French)

Fixes for Switzerland GE

---

holidays/countries/united_states.py

Two holidays that should apply to AR (Arkansas) incorrectly refer to the AS (American Samoa).

Fix incorrect abbreviations for Arkansas

---

README.rst
holidays/holiday_base.py
tests.py

I found it surprisingly hard to remove "Columbus Day" from the holiday list - the example code in the README works but it requires that the caller know when the holiday falls, but that's why I'm using the library! :)  So this PR adds a pop_named() call that does the reverse lookup and pop.

Add pop_named(), to make removing holidays easier.  No need to look up or calculate the date.

---

holidays/countries/singapore.py

A public holiday.
Source: https://www.mom.gov.sg/newsroom/press-releases/2020/0624-public-holiday-on-polling-day---10-july-2020

Added Singapore 2020 polling day

---

holidays/countries/singapore.py

Added movable public holidays for 2021.
Source: https://www.mom.gov.sg/newsroom/press-releases/2020/0624-public-holidays-for-2021

Added Singapore 2021 Public Holidays

---

holidays/countries/korea.py

* since date(2020,8,15) is Saturday, the government has decided to make date(2020,8,17) public holiday.
https://en.yna.co.kr/view/AEN20200721003200315
Done

Korea alternative holiday added

---

holidays/countries/australia.py
tests.py

The 2020 Royal Queensland Show (Ekka) holiday was moved to Friday 14
August 2020 for one year only.
See: https://www.qld.gov.au/recreation/travel/holidays/public

2020 Royal Queensland Show holiday moved

---

holidays/countries/united_states.py

This PR fixes https://github.com/dr-prodigy/python-holidays/issues/351 by removing the comma in the Idaho-specific MLK, Jr. holiday. I searched all countries and it appears that this is the only remaining comma included in a holiday name. This change removes any confusion with holidays falling on the same day being comma-separated.

fixed MLK comma issue

---

holidays/countries/croatia.py

Hi @dr-prodigy ,
I noticed that some names are partially incorrect and that some dates are incorrect so I fixed them. Below are holidays sources in Croatia. 
Cheers!
2020: https://mojkalendar.com.hr/
2019: https://mojkalendar.com.hr/2019.aspx

Croatian holidays fix

---

holidays/countries/australia.py
tests.py

This has been moved due to COVID-19.
Refer to: https://www.business.vic.gov.au/victorian-public-holidays-and-daylight-saving/victorian-public-holidays

Update Grand Final Public holiday for Victoria AU 2020.

---

holidays/countries/united_states.py
tests.py

The day after Thanksgiving is a state holiday as noted here https://www.calhr.ca.gov/employees/pages/state-holidays.aspx

Added day after Thanksgiving for California

---

holidays/countries/russia.py
tests.py

Up to 2004 there was no holiday on the November 4th. There was day-off holiday on November 7th - the day of October revolution. https://en.wikipedia.org/wiki/October_Revolution_Day
November 4th began holiday and day off only in 2005 and replaced November 7th.
There is question abount naming November 7th. This holiday was renamed twice. This is written in the paragraph "Post-Soviet observance" in wikipedia page above. Shoud we consider holiday renaming if in fact it stayed the same?

add October Revolution Day to Russian holiday

---

holidays/countries/united_kingdom.py

A small fix, just encountered your library and think highly of it and spotted something I could easily do.
The day after Christmas is not called "Boxing Day" in Ireland, it is called [St Stephen's Day](https://en.wikipedia.org/wiki/Saint_Stephen%27s_Day).

Day after Christmas is St Stephen's Day in Ireland

---

README.rst
holidays/countries/__init__.py
holidays/countries/france.py
tests.py

Closes #348 
As long as dateutil.relativedelta.FR is not imported within the FR class, which isn't, we're fine.

ISO code implementation for France

---

holidays/countries/singapore.py

I originally wrote this code and turns out that it had a bug that made the holidays for 2022 incorrect. Specifically, I had not fully implemented Section 4(2) of the Holidays Act: "if any day specified in the Schedule falls on a Sunday, the day next following _not being itself a public holiday_ is declared a public holiday in Singapore" (the part in italics was not implemented). This PR fixes it, for 2022 and any other year.
Also fixed a typo in line 200 (calcluate  -> calculate)

Fix Singapore for 2022

---

.travis.yml

Didn't implement it, but suggest dropping support of Python 3.5 since it was rendered obsolete by Python 3.6 on December 23, 2016

Travis tests for Python 3.9, released 2020-10-05

---

holidays/utils.py
tests.py

If `hijri-converter` package is not installed, fall back to using less precise `converdate` now that it's part of the installation (used for hebrew calendar) instead of skipping estimating of Hara Rasa Puasa and Hara Rasa Haji Singapore holidays.
Coverage will decrease since not all lines can be tested.

Fallback on convertdate if hijri-converter package is not installed

---

holidays/countries/united_kingdom.py
tests.py

UK will have an additional bank holiday on 2022 due to Queen's Platinum Jubilee (https://www.gov.uk/bank-holidays). It is updated in the code as it is a special holiday. Extended UK unit tests.

Extending UK holidays in 2022 for Queen's Jubilee

---

holidays/countries/japan.py
tests.py

Adding 2 days into Japan because these 1990-11-12 and 1993-06-09 are also national holidays in Japan according to [CSV file](https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv) published by Cabinet Office, Government of Japan.
**Check before code change**
```console
(ENV) C:\Users\sakurai\git\python-holidays>git rev-parse HEAD
3b24dcb11eab639ac7833d5ac95413b858f510a2
(ENV) C:\Users\sakurai\git\python-holidays>flake8 holidays\countries\japan.py tests.py
(ENV) C:\Users\sakurai\git\python-holidays>coverage run --omit=*site-packages* tests.py TestJapan
..................
----------------------------------------------------------------------
Ran 18 tests in 0.015s
OK
(ENV) C:\Users\sakurai\git\python-holidays>coverage report -m -i holidays\countries\japan.py
Name …
```

Add 1990-11-12 and 1993-06-09 into Japan

---

holidays/countries/india.py
holidays/countries/ireland.py
holidays/countries/united_kingdom.py
tests.py

To follow the homogeneous use in the rest of the Countries, I propose to modify the value of 'country' by the Alpha-2 code of the ISO-3166 standard.
https://www.iso.org/glossary-for-iso-3166.html

Use Alpha-2 code as 'country'

---

holidays/countries/japan.py
test/countries/test_japan.py

Thank you for your great work.
I fixed data for Japan according to the [Japanese Cabinet Office's data](https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv).
- remove foundation day before 1967
- add a substitute holiday (1974-05-06).
- add public holidays (1959-04-10, 1989-02-24)

Fix jp holidays

---

holidays/countries/serbia.py
test/countries/test_serbia.py

When one of the holiday days falls on Sunday, it is observed on next working day. Second day of Labour Day (May 2nd) is Sunday this year, which is also Orthodox Easter, so this year first working day is 4th of May.

fixed easter&labour day for serbia 2021

---

holidays/countries/united_kingdom.py
test/countries/test_united_kingdom.py

The `get_list` method assumes that commas are not used in the names of individual holidays, by splitting overlapping holidays according to commas:
https://github.com/dr-prodigy/python-holidays/blob/cb875fb87e91f8c555966659bca1636519c47d6f/holidays/holiday_base.py#L144-L145
Violations of this assumption have come up before in #295 and #351 and been fixed by removing the comma.
There are some commas in UK holiday names causing the same problem:
```Python
import datetime
import holidays
uk_holidays = holidays.UK(years=[2021])
x = uk_holidays.get_list(datetime.date(2021, 8, 30))
print(x)
```
where it is split into a 3-element list instead of being a single element.
This fixes it by removing the commas. After the fix, the code above prints `['Late Summer Bank Holiday [England/Wales/Northern …

Remove commas from UK holidays

---

.pre-commit-config.yaml
holidays/countries/jamaica.py
holidays/countries/south_africa.py
requirements_dev.txt
setup.cfg
setup.py

[As mentioned](https://github.com/dr-prodigy/python-holidays/pull/404#issuecomment-811237868), using a `setup.cfg` only pattern has the benefit (as does `bump2version`) that you only have to manage the version string in one place but in contrast to `bump2version` you don't need to take care of all the version parsing, replacing and especially that bug with the trailing whitespace which together with `pre-commit` nullifies all the benefits of `bump2version`.
1. Change the version  string of `__version__` in `holidays/.__init__.py` to the desired value (push or PR)
2. Create a new release in the [release tab](https://github.com/dr-prodigy/python-holidays/releases), this will also create a tag
3. Wait for the CI to publish it to PyPi 🎉 
Here is also [proof that the release …

Use setup.cfg only pattern instead of bump2version

---

holidays/countries/singapore.py
test/countries/test_singapore.py

Freshly released per https://www.mom.gov.sg/employment-practices/public-holidays

Added Singapore official holidays for 2022

---

holidays/countries/spain.py
test/countries/test_spain.py

Hi @dr-prodigy 
AFAIK, _Good Friday_ (2021-04-02 this year) is one of the few **national** holidays in Spain, (and it's also defined as that in https://www.timeanddate.com/holidays/spain/good-friday), but in the library it is ~~strangely~~ excluded from 2 states ("CT", "VC")
This PR removes that scenario, adding it as holiday for the full country. 
Also closes #468 :)
More detailed info can be found in a table in this PDF from the Official Gazette about the holidays for 2021 (section 'ANEXO Año 2021'): https://www.boe.es/boe/dias/2020/11/02/pdfs/BOE-A-2020-13343.pdf

Fix Spain Good Friday (#468)

---

holidays/countries/united_states.py
test/countries/test_united_states.py

The US has passed a bill making Juneteenth National Independence Day a federal legal public holiday (June 19th). This PR adds the holiday.
Senate bill: https://www.congress.gov/bill/117th-congress/senate-bill/475/text
This change also updates tests for Emancipation Day in Texas beyond 2021, since it had asserted that there was no federal holiday on June 19th.
Closes #475

Add Juneteenth National Independence Day to US

---

holidays/countries/botswana.py

If a public holiday falls on an observed holiday, that public holiday is observed the next day. 
To implement this get the public holidays after adding the observed holidays and then splitting strings where more than one holidays falls on a date.
Added .lstrip() to this in order to remove the leading space

Strip leading whitespace Botswana holiday movement

---

holidays/countries/united_kingdom.py

The Spring Bank Holiday is normally the last Monday in May. In 2022 it is moving to 2nd June to allow for a four day weekend, as per https://www.gov.uk/bank-holidays

Correct 2022 Spring Bank Holiday

---

README.rst

This closes #484.
I used a convenience function for sorting, keeping it documented here for quick access.
```python
sortme = lambda p: ', '.join(sorted([str(x) for x in p.split(", ")]))
prov = "NTL, AUK, TKI, HKB, WGN, MBH, NSN, CAN, STC, WTL, OTA, STL, CIT"
sortme(prov)
```

Update readme file: alphabetically order "prov/state" entries

---

holidays/holiday_base.py
requirements_dev.txt
setup.cfg

We no longer support Python 2 so importing `six` no longer has any utility.
I have replaced the only instance of the module usage with the Python 3 equivalent (see https://six.readthedocs.io/#six.string_types) and have removed `six` as a project dependency.  Fixing typos (space missing) is a side benefit ;)

Removed dependency on six

---

holidays/countries/new_zealand.py
test/countries/test_new_zealand.py

Add Matariki for New Zealand
Dates from here: https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf

New Zealand: Matariki

---

.gitignore
holidays/countries/kenya.py
test/countries/test_kenya.py

- Added a new Kenyan Holiday I noticed missing Huduma (translated Service) day on the 10th of October. Reference for this change can be found [here](https://citizentv.co.ke/news/govt-renames-moi-day-to-huduma-day-boxing-day-to-utamaduni-day-309914/).
- Renamed the Boxing day holiday (26th December), which was officially changed to Utamaduni(translated Cultural) day. Reference for this change can be found [here](https://en.wikipedia.org/wiki/Public_holidays_in_Kenya) and also [here](https://www.tuko.co.ke/261515-gazetted-public-holidays-kenya.html#:~:text=Huduma%20Day%20%2D10th%20October&text=Huduma%20Day%20is%20a%20public,declaration%20of%20the%20new%20constitution.)

Add new Kenyan holiday and edit existing one

---

holidays/countries/korea.py
test/countries/test_korea.py

https://www.officeholidays.com/holidays/south-korea/south-korea-liberation-day
https://www.koreatimes.co.kr/www/opinion/2021/07/202_310642.html
since 2021, the liberation day has alt holiday when it's on the weekend

give Korea liberation day an alt_holiday

---

.pre-commit-config.yaml
holidays/__init__.py
holidays/holiday_base.py
holidays/utils.py

It's time we added type hints to make this package a bit more developer-friendly, so here's my first contribution to type hinting and docstring inline documentation (which I developed out of frustration while reviewing the Malaysian submission over the weekend).
While adding type hints I have encountered a few things in the `HolidayBase` class I simply could not avoid having to refactor, and a few that needed cleaning up:
* In `__init__` method:
* The attribute `PROVINCES` was unused and has been removed.
* The call to the `__init__` of the superclass was missing and has been added.
* Code that turns years into a set has been cleaned up.
* Switched to iterating years over set().copy() instead of list(set()). I contributed the original code change, which avoided corner cases of …

Type hinting and docstrings

---

holidays/countries/australia.py
test/countries/test_australia.py

The 2021 Royal Queensland Show (Ekka) holiday was moved to Friday 29 October.
See https://www.qld.gov.au/recreation/travel/holidays/public

Australia\QLD Royal Queensland Show holiday moved for 2021.

---

holidays/countries/australia.py
test/countries/test_australia.py

I have made a quick change to the Public Holiday generation algorithm for Australia which adds a special case for the 2021 grand final date being Friday 24/SEP/2021. Every year should be a special case for grand final day as it can change depending on the needs of the AFL and is not fixed. 
I have created a simple test case for this in the test_grand_final test function.

Australia Vic Grand Final Day 2021 Special Case Added

---

holidays/holiday_base.py

Fix for #527 (assuming the `array` in the code posted was `numpy.array`).  
`years` is typed as Iterable, so a `numpy.array` should be accepted.
If I inadvertently introduced the issue, apologies.
before:
```
import holidays
import numpy
print(holidays.__version__)
years = numpy.array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])
holidays.CZ(years=years)
0.11.3
Traceback (most recent call last):
File "C:\Program Files\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-2-b11133d668e1>", line 5, in <module>
holidays.CZ(years=years)
File "C:\Users\user\Documents\python\git_repos\python-holidays\holidays\countries\czechia.py", line 29, in __init__ …
```

numpy iterable compatibility

---

holidays/countries/canada.py
test/countries/test_canada.py

Earlier this year the government of Canada announced a new federal holiday, National Day for Truth and Reconciliation. For 2021, two provinces have adopted this day as an official holiday: Manitoba and Nova Scotia. 
i'd expect by next year more to follow and will update accordingly at that time. 🇨🇦

Canada :: National Day for Truth and Reconciliation

---

test/countries/test_canada.py

there were only a couple missing tests to bump Canada holiday test coverage from 97% -> 100%. this gets that done 🇨🇦 🍁 🏒 
```
$> pytest test/countries/test_canada.py
========================== test session starts ===============================
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /python-holidays, configfile: tox.ini
plugins: cov-2.12.1
collected 20 items
test/countries/test_canada.py ....................                       [100%]
----------- coverage: platform linux, python 3.9.2-final-0 -----------
Name                                          Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------
[...]
holidays/countries/canada.py                    154      0    114      0   100% …
```

full test coverage for Canadian holidays

---

holidays/countries/united_states.py
test/countries/test_united_states.py

Addresses #503 
This adds support for the observed occurrences of United States Juneeteenth (June 19) holiday.  2021 and 2022 both have observed dates - (2021/06/18, 2022/06/20).  This small snippet should future proof the observed dates.

add Juneteenth Observed holiday support

---

holidays/countries/spain.py
test/countries/test_spain.py

The only way to add tests for province holidays changing in time was to write a separate test.
Closes #544

support Spain

---

README.rst
holidays/countries/__init__.py
holidays/countries/tunisia.py
test/countries/test_tunisia.py

I have added the National public holidays of Tunisia.
The dates of the following holidays are announced yearly and estimated:
* Eid El Fetr
* Eid El Adha
* Arafat Day
* El Moulad

Add public holidays of Tunisia

---

holidays/countries/colombia.py

- Update discovery of América to Columbus Day
- Use accented í for día
I'm colombian and we don't call that day "Discovery of America" but "Columbus day" and "Día de la raza" in Spanish.
Thanks!

Update colombian holidays

---

holidays/countries/__init__.py

Fix missing import for `NorthMacedonia` class/country.

Add `NorthMacedonia` import to __init__

---

holidays/countries/united_states.py
test/countries/test_united_states.py

Like other US holidays, if `Juneteenth National Independence Day` falls on a Saturday, it will be observed on Friday (and for Sunday it will be observed on Monday). Added the support for that and appropriate tests.

Add Observed support for Juneteenth Day

---

holidays/countries/united_states.py

Fixes https://github.com/dr-prodigy/python-holidays/issues/594
Before:
```
>>> us_holidays=holidays.UnitedStates()
>>> us_holidays.get('June 20, 2022')
'Confederate Memorial Day (Observed)'
```
After:
```
>>> us_holidays=holidays.UnitedStates()
>>> us_holidays.get('June 20, 2022')
'Juneteenth National Independence Day (Observed)'
```

Fix Juneteenth name bug

---

holidays/countries/burundi.py
holidays/countries/djibouti.py
holidays/countries/egypt.py
holidays/countries/morocco.py
holidays/countries/nigeria.py
holidays/countries/saudi_arabia.py
holidays/countries/tunisia.py
holidays/countries/turkey.py
holidays/countries/united_arab_emirates.py
holidays/holiday_base.py
test/countries/test_azerbaijan.py
test/countries/test_india.py
test/countries/test_saudi_arabia.py
test/countries/test_singapore.py
test/test_holiday_base.py

While working on an another PR I discovered that  my PR #586 (Do not expand into other years) was incomplete: I missed that holidays for Saudi Arabia for 2006 would also return holidays for 2007, violating the "do not expand into other years" rule and triggering the "dict expansion while iterating" error in people's code.
The issue, it turns out, is multi-day Islamic holidays; in this specific case it was the Eid al-Adha Holiday running from 30-Dec-2006 to 03-Jan-2007, across Gregorian years.
Here is a fix for this issue, covering Saudi Arabia and all other countries affected. It's not very elegant but I couldn't think of a better solution (open to ideas). The fix has been successfully tested on all years from 1950 to 2050 inclusive.
I also addressed:
* The Saudi Arabia tests had some …

Do not expand into other years v2

---

.pre-commit-config.yaml
MANIFEST.in
docs/source/conf.py
holidays/countries/korea.py
holidays/holiday_base.py
holidays/py.typed
holidays/utils.py
test/countries/__init__.py
tox.ini

* Implemented [mypy](http://mypy-lang.org/) static type checker in pre-commit
* Updated pre-commit to current versions ($ [pre-commit autoupdate](https://pre-commit.com/#pre-commit-autoupdate))
* Added `py.typing` file to implement [PEP 561 packaging type information](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)
* Minor cleanup of errors in static typing / incompatibilities with mypy and addition of `# type: ignore`

mypy implementation

---

holidays/countries/australia.py
test/countries/test_australia.py

G'day,
Would it be possible to merge this branch into the master / main branch. This branch contains a commit that sets the date of Grand Final Day for the year 2022 in Vic to the 23rd of September. Unlike regular public holidays Grand Final Day changes with the corporate needs of the AFL. Please feel free to provide any critiques or changes that will need to be made. 
Jeremy 🙂

AU-VIC Set Grand Final Day for 2022 (2022-09-23)

---

holidays/countries/ireland.py

fix: Update Irish bank holidays

---

holidays/countries/saudi_arabia.py
test/countries/test_saudi_arabia.py

- Add new [founding day](https://english.alarabiya.net/News/gulf/2022/01/27/Saudi-Arabia-to-commemorate-Founding-Day-on-Feb-22-annually-Royal-order) holiday to Saudi Arabia module
- Add tests for new "founding day" holiday
- Add tests for weekend shifts that happened at 2013 (from Thrusday, Friday weekend to Friday, Saturday weekend)
- Fix weekend check for national holiday to include previous weekends (before 2013)
- Fix weekend code that mistakenly add UAE weekends into Saudi Arabia
- Add tests for edge cases when overlapping holidays between hijri and gregorian calendars

Add founding day holiday to Saudi Arabia holidays

---

holidays/countries/spain.py
test/countries/test_spain.py

The `_is_observed` funtion takes care about observed dates, so no need to add them as 'observed' dates.
The tests have also been fixed so that they run correctly. In this case, the validations have to be done on the `observed` dates.

Fix Spain 'observed' date

---

holidays/countries/singapore.py
test/countries/test_singapore.py

Added official movable holiday dates for 2023, which have been announced today, and updated testing: https://www.straitstimes.com/singapore/singapore-to-have-6-long-public-holiday-weekends-in-2023
Official source: https://www.mom.gov.sg/employment-practices/public-holidays

SG 2023 final dates

---

holidays/countries/greece.py
test/countries/test_greece.py

https://www.timeanddate.com/holidays/greece/labor-day
https://en.wikipedia.org/wiki/Public_holidays_in_Greece
From the wikipedia article:
> A public holiday that occurs on a Sunday is not transferred to another date, with the exception of 1 May, which is regarded by the locals more as a general strike than a public holiday.

Add special cases for observing Labour Day in Greece

---

holidays/countries/poland.py
test/countries/test_poland.py

`Uroczystość Wszystkich świętych` -> `Uroczystość Wszystkich Świętych`  
references:
* https://pl.wikipedia.org/wiki/Dni_wolne_od_pracy_w_Polsce
* https://pl.wikipedia.org/wiki/Uroczystość_Wszystkich_Świętych
* https://pl.wiktionary.org/wiki/Wszystkich_Świętych
(also, added a new test case to bump `poland.py` test coverage to 100%)

fix capitalization typo (Poland - Uroczystość Wszystkich Świętych)

---

setup.cfg

The py.typed that was added at #620 is not being published, so no users of this library can take advantage of the types that it exposes.

include py.typed in published package

---

setup.cfg

This addresses https://github.com/dr-prodigy/python-holidays/issues/670 which is also breaking the conda-forge build.

Fix missing holidays.financial

---

holidays/countries/ukraine.py
test/countries/test_ukraine.py

- Add Day of Ukrainian Statehood holiday.
- Edit Victory Day name.
- Fix formatting.
- Update tests for Ukraine holidays.
- Switch to <= and >= for consistency.
- Rename Orthodox Easter.

Update Ukraine holidays.

---

holidays/countries/colombia.py
test/countries/test_colombia.py

Colombia essentially has four types of holidays:
1. fixed non-easter based
2. flexible non-easter based
3. fixed easter based
4. flexible easter based
The easter based holidays depend on when easter occurs. The flexible holidays occur on the next Monday after the date the holiday falls on, unless it already falls on a Monday.
This change does the following:
1. fixes non-easter based holidays not being set (ie: new year's wasn't being set for 2022: https://github.com/dr-prodigy/python-holidays/issues/674).
2. I rigorously went through the Colombian laws and decrees about holidays and labour since 1905 (wasn't precisely codified until 1939) and went through examples of physical calendars to verify this. Proof is in the code as comments.
3. I improved the test cases to increase confidence in …

Make Colombian holidays preserve historical observation

---

holidays/countries/venezuela.py
test/countries/test_venezuela.py

I rigorously went back through the historical records by analyzing laws and decrees until 1909 to get an accurate representation of what holidays there were over the years. I added many more test cases to increase confidence in the code. I put the proof for each year I picked in the code.
For some holidays, such as declaration of independence, I put conservative dates such as when they declared independence because I could not find any laws or decrees in the historical record before 1909.
There is one holiday that was in a decree in 1909 and was overturned in 1918. I tried my best to find out what it was called, but could not unfortunately.

Make Venezuela holidays preserve historical observation

---

holidays/financial/ny_stock_exchange.py
test/financial/test_ny_stock_exchange.py

Resolves #693 
Fix New Year observance for Saturdays:
- Make NYD observance complied with NYSE official regulations (Rule 7.2.).
- Remove out of date comment URLs.
- Simplify `_get_observed` method code.
- Fix corner case for next year's Saturday NYD.
- Add tests.

Fix New Year observance for Saturdays.

---

holidays/countries/australia.py
test/countries/test_australia.py

The Australian government has announced the 22rd of September 2022 will be a once-off public holiday to mourn the death of Queen Elizabeth II.
https://www.abc.net.au/news/2022-09-11/national-day-of-mourning-queen-death-to-be-public-holiday/101427050
The grand final day holiday is confirmed for the Friday 23rd so I've removed the comments stating it is still in question
https://www.afl.com.au/news/763512/afl-confirms-2022-toyota-grand-final-start-time
First time contributor so please let me know if I've made any missteps and I'll be more than happy to correct them.

Add Australia National Day of Mourning and confirmed Grand Final Day date

---

holidays/countries/canada.py
test/countries/test_canada.py

The queen's funeral will be a holiday federally and in some provinces and territories. However, the default is ON and not federal so the federal holiday logic isn't here.

Add queen's funeral holidays for canada

---

holidays/holiday_base.py
test/countries/test_brazil.py
test/test_holiday_base.py

Resolves #705 
Order holidays by name when there are multiple holidays on the same date.

Sort holiday names.

---

holidays/countries/canada.py

For Canada, Christmas and Boxing day were now showing the non-observed day, unlike the other holidays for Canada.

Fix observed holiday for christmas and boxing day canada

---

holidays/countries/__init__.py
holidays/countries/eswatini.py
test/countries/test_eswatini.py

This country has a different name now (but keep it backwards-compatible).

Rename Eswatini from Swaziland

---

README.rst

Looks like the docs have a typo for the Yukon Territory (YU should be YT). In the code this seems to be correct.
https://en.wikipedia.org/wiki/ISO_3166-2:CA

Fixed incorrect subdivision code

---

README.rst

Adding an extra entry like the Alpha-3 code in the countries table causes render failure
By removing this line, the table is displayed correctly.

README.rst: Remove Alpha-3 code for Bosnia and Herzegovina

---

holidays/countries/__init__.py
holidays/countries/isle_of_man.py
holidays/utils.py
test/test_holiday_base.py

Resolves #762 
Replace `obj.__base__` with `issubclass`.
Add Isle Of Man alpha-3 code.

Fix `list_supported_countries` and `list_supported_financial` methods.

---

holidays/countries/brazil.py
test/countries/test_brazil.py

From 2017 onwards if the 11th of August falls on a work day the holiday is moved to the next Sunday.
Issue: 592

brazil.py: Update SC holiday according 2017 law

---

holidays/countries/lithuania.py
test/countries/test_lithuania.py

2nd of November is a holiday in Lithuania (https://publicholidays.lt/2022-dates/)
issue-774

lithuania: add the 2nd on November as holiday

---

.pre-commit-config.yaml
holidays/countries/botswana.py
holidays/countries/eswatini.py
holidays/countries/hongkong.py
holidays/countries/ireland.py
holidays/countries/japan.py
holidays/countries/korea.py
holidays/countries/lesotho.py
holidays/countries/malaysia.py
holidays/countries/namibia.py
holidays/countries/poland.py
holidays/countries/singapore.py
holidays/countries/slovakia.py
holidays/countries/south_africa.py
holidays/countries/zambia.py
test/countries/test_botswana.py
test/countries/test_eswatini.py
test/countries/test_hongkong.py
test/countries/test_ireland.py
test/countries/test_korea.py
test/countries/test_lesotho.py
test/countries/test_namibia.py
test/countries/test_poland.py
test/countries/test_singapore.py
test/countries/test_slovakia.py
test/countries/test_south_africa.py

As #724 has been recently merged the next step is to migrate the rest of the countries to use the new approach.
Move logic from `_populate` to `special_holidays` for:
- Botswana
- Eswatini
- Hongkong
- Ireland
- Japan
- South Korea
- Lesotho
- Namibia
- Poland
- Singapore
- Slovakia
- South Africa
- Zambia

Special holidays migration

---

holidays/countries/canada.py
test/countries/test_canada.py

The Canadian rules are ambiguous w.r.t. where to place the observed day when a statutory holiday falls on a weekend. According to Wikipedia the observed day can come before or after the holiday:
https://en.wikipedia.org/wiki/Public_holidays_in_Canada#Holidays_occurring_on_non-work_days
However, in the case of NYD, this has historically been falling after new year's. Since 1980 NYD has fallen on a Saturday six times (1983, 1994, 2000, 2005, 2011, and 2022). In all cases, the TSX (Toronto Stock Exchange) has had data on December 31st (the Friday) and no data on January 3rd (the following Monday).
Similarly, NYD has fallen on a Sunday seven times (1978, 1984, 1989, 1995, 2006, 2012, 2017). A similar pattern is observed there; data on Dec 30th and no data on Jan 2nd. For national markets at …

Canada: make observed New Year's Day fall on or after the holiday

---

holidays/financial/ny_stock_exchange.py
test/financial/test_ny_stock_exchange.py

Adding a new financial holiday - Day of Mourning for President George H.W. Bush 
https://eu.usatoday.com/story/money/2018/12/03/stock-market-closed-december-5-george-h-w-bush/2192106002/

Financial holiday - Day of Mourning for President George H.W. Bush

---

holidays/financial/ny_stock_exchange.py
test/financial/test_ny_stock_exchange.py

Hurricane sandy - October 29 & 30, 2012
Hurricane Gloria - September 27th, 1985
https://www.sandiegouniontribune.com/sdut-hurricane-sandy-shuts-stock-trading-for-2-days-2012oct29-story.html

Adding financial holidays - Hurricane Gloria and Sandy

---

holidays/countries/south_africa.py
test/countries/test_south_africa.py

Alternative for #837 and #839, using `special_holidays`

South Africa: added 27 Dec 2022 public holiday

---

requirements_dev.txt

Add a temporary version pin in order to fix GH CI/CD.

Pin `coverage` version

---

holidays/financial/ny_stock_exchange.py
test/financial/test_ny_stock_exchange.py

Election Day is Tuesday after first Monday in November, not first Tuesday

NYSE: fix Election Day holiday

---

holidays/countries/south_korea.py

Change KO, KOR parent from `Korea` to `SouthKorea`.

Fix South Korea deprecation warnings.

---

test/countries/test_argentina.py
test/countries/test_australia.py
test/countries/test_austria.py
test/countries/test_bulgaria.py
test/countries/test_canada.py
test/countries/test_colombia.py
test/countries/test_cuba.py
test/countries/test_ireland.py
test/countries/test_israel.py
test/countries/test_mexico.py
test/countries/test_new_zealand.py
test/countries/test_pakistan.py
test/countries/test_paraguay.py
test/countries/test_united_kingdom.py
test/countries/test_united_states.py
test/countries/test_uruguay.py
test/countries/test_venezuela.py
test/countries/test_vietnam.py
test/financial/test_european_central_bank.py
test/financial/test_ny_stock_exchange.py
test/test_holiday_base.py

Resolves https://github.com/dr-prodigy/python-holidays/issues/891
This PR contains tests only changes. See #900 for the business logic changes.

Refactor days offset calculation: replace `relativedelta` with `timedelta` (tests)

---

holidays/utils.py
test/countries/test_bahrain.py
test/countries/test_djibouti.py
test/countries/test_egypt.py
test/countries/test_morocco.py
test/countries/test_tunisia.py
test/countries/test_united_arab_emirates.py

- fix for holidays that happen twice in a Gregorian year (primarily islamic New Year)
- years range checking more strictly

Fix Islamic holidays calculation

---

holidays/countries/burundi.py

Performance tests:
```
def calc_hol1():
for year in range(1962, 2100):
hols = Burundi(years=year)
def calc_hol2():
hols = Burundi(years=range(1962, 2100))
t1 = timeit.timeit(calc_hol1, number=100)
t2 = timeit.timeit(calc_hol2, number=100)
```
| Test | Current beta |   PR  |
|:----:|:------------:|:-----:|
|  t1  |        3.114 | 3.117 |
|  t2  |        6.797 | 2.920 |

Optimize Burundi observed holidays

---

holidays/countries/ukraine.py
test/countries/test_ukraine.py

Performance tests:
```
country = "UA"
START_YEAR = 1917
END_YEAR = 2099
def calc_hol1():
for year in range(START_YEAR, END_YEAR + 1):
hols = holidays.country_holidays(country, years=year)
def calc_hol2():
hols = holidays.country_holidays(country, years=range(START_YEAR, END_YEAR + 1))
t1 = timeit.timeit(calc_hol1, number=100)
t2 = timeit.timeit(calc_hol2, number=100)
```
| Test | Current beta |   PR  |
|:----:|:------------:|:-----:|
|  t1  |        2.290 | 2.219 |
|  t2  |       19.376 | 1.925 |

Optimize Ukraine observed holidays

---

README.rst
holidays/countries/united_states.py

Only US Federal Holidays are "observed".  From Wikipedia: 
> Except for [Palmyra Atoll](https://en.wikipedia.org/wiki/Palmyra_Atoll), all of these islands are [unincorporated](https://en.wikipedia.org/wiki/Territories_of_the_United_States#Incorporated_vs._unincorporated_territories) [unorganized territories of the United States](https://en.wikipedia.org/wiki/Territories_of_the_United_States#Organized_vs._unorganized_territories). Currently, none of the islands have any permanent residents, although military personnel, U.S. Fish and Wildlife Service personnel, and temporarily stationed scientific and research staff are posted to some of the islands

Add United States Minor Outlying Islands (ISO-3666-2 code US-UM)

---

holidays/countries/angola.py
holidays/countries/armenia.py
holidays/countries/azerbaijan.py
holidays/countries/belarus.py
holidays/countries/botswana.py
holidays/countries/bulgaria.py
holidays/countries/burundi.py
holidays/countries/canada.py
holidays/countries/chile.py
holidays/countries/china.py
holidays/countries/eswatini.py
holidays/countries/germany.py
holidays/countries/hongkong.py
holidays/countries/madagascar.py
holidays/countries/malawi.py
holidays/countries/mozambique.py
holidays/countries/namibia.py
holidays/countries/new_zealand.py
holidays/countries/nigeria.py
holidays/countries/pakistan.py
holidays/countries/slovenia.py
holidays/countries/south_africa.py
holidays/countries/thailand.py
holidays/countries/ukraine.py
holidays/countries/united_states.py
holidays/countries/zambia.py
holidays/countries/zimbabwe.py
tests/countries/test_bahrain.py
tests/countries/test_ethiopia.py

Use `return None` instead of just `return`.

Refactor implicit returns

---

holidays/countries/canada.py
tests/countries/test_canada.py

https://www.cbc.ca/news/canada/british-columbia/bc-truth-and-reconciliation-day-statutory-holiday-1.6740033

National Day for Truth and Reconciliation in British Columbia (Canada) since 2023

---

holidays/countries/angola.py
holidays/countries/eswatini.py
holidays/countries/kazakhstan.py
holidays/countries/kenya.py
holidays/countries/malawi.py
holidays/countries/singapore.py
holidays/countries/south_africa.py
tests/countries/test_angola.py
tests/countries/test_eswatini.py
tests/countries/test_kazakhstan.py
tests/countries/test_kenya.py
tests/countries/test_malawi.py

Angola, Eswatini, Kazakhstan, Kenya, Malawi, Singapore, South Africa

Optimize observed holidays, part 2

---

.gitignore
.pre-commit-config.yaml
.readthedocs.yaml
Makefile
tox.ini

The fix and related changes include:
- Add .readthedocs.yaml.
- Update .gitignore.
- Update .pre-commit-config.yaml.
- Update Makefile.
- Update tox.ini.

Fix readthedocs.io build

---

holidays/calendars.py
holidays/countries/canada.py
holidays/countries/united_states.py
tests/test_calendars.py

Optimize relative weekdays calculation. Most common cases of `dateutil.relativedelta` use (n-th weekday of month, n-th weekday from date) replaced with own simple functions. To start, I chose 2 countries that have many such holidays - US and Canada.
Perhaps functions names need to be corrected. :)

Add functions for relative weekdays calculation

---

holidays/holiday_base.py
tests/common.py
tests/countries/test_chile.py
tests/test_holiday_base.py

The PR aims to impove `HolidayBase::get_named` flexibility in terms of available holiday name lookup types:
- Add `lookup` parameter.
- Add `contains/iexact/icontains/iexact` lookup types.
- Keep the current behavior with `icontains` as default lookup type.

Refactor `HolidayBase::get_named`

---

holidays/countries/chile.py
holidays/countries/japan.py
setup.cfg

Use the built-in library for timezone functions.
Benefits:
* Implemented best practice of using built-in libraries when possible;
* Improved speed of line 120 of ``chile.py`` by ~1.6x;
* Removed dependency on external package ``python-dateutil`` for timezone.

Use the built-in library for time zone functions

---

holidays/countries/thailand.py
holidays/locale/en_US/LC_MESSAGES/TH.po
holidays/locale/th/LC_MESSAGES/TH.po

This standardizes Thailand's localization file by removing extra comments from running `make l10n` and standardizing in-line comments for codes in `Thailand.py` file as per @arkid15r 's styling recommendation mentioned in #988 .

Clean up Thailand localization and in-line code comments

---

holidays/financial/ny_stock_exchange.py
tests/financial/test_ny_stock_exchange.py

When New Year falls on Saturday, observed holiday falls on Dec 31 of the previous year and we received error `RuntimeError: Set changed size during iteration`.

Fix NYSE New Year's Day observance calculation

---

README.rst

This adds the missing `th` support for Canada in the readme file that was added in #986 which has since been merged for 0.21 release. No other changes are done to the codebase.

Update README: add missing th localization for Canada

---

tests/test_utils.py

Resolves #1007 
Update country/financial years tests.
Add financial 1950-2050 years tests.

Update country/financial years tests

---

README.rst
holidays/countries/__init__.py
holidays/countries/el_salvador.py
holidays/registry.py
tests/countries/test_el_salvador.py

Add El Salvador holidays (close #1177).

Add El Salvador holidays

---

holidays/countries/cuba.py
holidays/locale/en_US/LC_MESSAGES/CU.po
holidays/locale/es/LC_MESSAGES/CU.po
holidays/locale/uk/LC_MESSAGES/CU.po
tests/countries/test_cuba.py

Migrate Cuba holidays to `holiday_groups` standard.
This PR also adds a cut-off date for 1959 to prevent Cuban Revolution holidays from firing before the event.

Migrate Cuba holidays to holiday groups

---

holidays/countries/vatican_city.py
tests/countries/test_vatican_city.py

This PR migrates the two remaining international holidays for the Vatican (New Year's Day and Labor Day) to their respective holiday groups. 
While ["Solemnity of Mary Day"](https://www.ewtn.com/catholicism/library/solemnity-of-mary-mother-of-god-5826) was only adopted by the entire Latin Church in 1931, this matches the already existing Octave Day of Christmas celebrations in Rome so I'm going to leave this untouched for now.
["Saint Joseph the Worker's Day"](https://www.franciscanmedia.org/saint-of-the-day/saint-joseph-the-worker/) feast is also corrected to only appear from 1955 onwards (this was instituted by Pope Pius XII).
[docs]: …

Update Vatican City holidays: add Saint Joseph the Worker's Day introduction year check

---

holidays/holiday_base.py

SSIA. Naive UTC ones are deprecated as of Python 3.12.

Use aware UTC datetimes internally

---

tests/common.py
tests/countries/test_azerbaijan.py

Now `assertHolidayName/assertNoHolidayName` methods, if parameter is a sequence of dates, check for the presence/absence of **these dates in holiday list**, instead of checking for presence of **holiday with the specified name on these dates**.

Fix common::TestCase methods

---

README.rst
holidays/countries/bulgaria.py
holidays/locale/bg/LC_MESSAGES/BG.po
holidays/locale/uk/LC_MESSAGES/BG.po
tests/countries/test_bulgaria.py

Migrate Bulgaria holidays to holiday groups and categories, add uk localization.

Migrate Bulgaria holidays to holiday groups and categories

---

README.rst
holidays/countries/indonesia.py
holidays/locale/en_US/LC_MESSAGES/ID.po
holidays/locale/id/LC_MESSAGES/ID.po
holidays/locale/uk/LC_MESSAGES/ID.po
tests/countries/test_indonesia.py

Update Indonesia holidays:
- add l10n support (en_US, **id**, uk)
- add historical holidays

Update Indonesia holidays, add l10n support

---

holidays/countries/japan.py
holidays/locale/en_US/LC_MESSAGES/JP.po
holidays/locale/ja/LC_MESSAGES/JP.po
tests/countries/test_japan.py

Add Japan bank holidays (Dec 31, Jan 2 and 3).

Update Japan holidays: add bank holidays

---

holidays/countries/namibia.py
holidays/countries/netherlands.py
holidays/countries/new_zealand.py
holidays/countries/nicaragua.py
holidays/countries/nigeria.py
holidays/countries/north_macedonia.py
holidays/countries/norway.py
holidays/countries/pakistan.py
holidays/countries/panama.py
holidays/countries/paraguay.py
holidays/countries/peru.py
holidays/countries/philippines.py
holidays/countries/poland.py
holidays/countries/portugal.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ n-p.

Use HolidayBase::_add_holiday_* family methods [n-p]

---

README.rst
holidays/countries/__init__.py
holidays/countries/vanuatu.py
holidays/registry.py
tests/countries/test_vanuatu.py

Your PR description goes here.

Add Vanuatu holidays

---

holidays/countries/slovenia.py
holidays/locale/en_US/LC_MESSAGES/SI.po
holidays/locale/sl/LC_MESSAGES/SI.po
holidays/locale/uk/LC_MESSAGES/SI.po
tests/countries/test_slovenia.py

This PR adds the "Solidarity Day" public holiday for Slovenia for August 14th 2023. 
https://en.wikipedia.org/wiki/Public_holidays_in_Slovenia

Update Slovenia holidays: add 2023 Solidarity Day

---

.pre-commit-config.yaml
holidays/holiday_base.py

Resolves #1427 
Use typing cast for HolidayBase::__eq__
Fix Unsupported operand types for == ("Mapping" and "HolidayBase") error.
Bump mypy version from 1.4.1 to v 1.5.0

Use typing cast for HolidayBase::__eq__

---

holidays/countries/barbados.py
tests/countries/test_barbados.py

Update Barbados holidays:
- add observed holidays
- add start dates for some holidays
- add tests

Update Barbados holidays

---

.github/workflows/ci-cd.yml
tox.ini

Add latest Python 3.12 release to tests (without specifying a certain version).

Add latest Python 3.12 release to tests

---

holidays/countries/belgium.py
holidays/locale/de/LC_MESSAGES/BE.po
holidays/locale/en_US/LC_MESSAGES/BE.po
holidays/locale/fr/LC_MESSAGES/BE.po
holidays/locale/nl/LC_MESSAGES/BE.po
holidays/locale/uk/LC_MESSAGES/BE.po
tests/countries/test_belgium.py

Update Belgium holidays: add bank holidays.
It's a bit strange, but Dec 26 holiday name in German, Dutch and French is "Bank Holiday" ([DE](https://www.nbb.be/de/die-nationalbank/die-nationalbank/arbeitsfreie-tage), [NL](https://www.nbb.be/nl/over-de-nationale-bank/de-nationale-bank/sluitingsdagen), [FR](https://www.nbb.be/fr/la-banque-nationale/la-banque-nationale/jours-de-fermeture)).

Update Belgium holidays: add bank holidays

---

holidays/countries/barbados.py
holidays/countries/bulgaria.py
holidays/countries/burundi.py
holidays/countries/hongkong.py
holidays/countries/vanuatu.py
holidays/locale/bg/LC_MESSAGES/BG.po
holidays/locale/en_US/LC_MESSAGES/BG.po
holidays/locale/uk/LC_MESSAGES/BG.po
tests/countries/test_bulgaria.py
tests/countries/test_vanuatu.py

Migrate remaining countries to `ObservedHolidayBase` (Barbados, Bulgaria, Burundi, Hong Kong, Vanuatu).

Migrate remaining countries to ObservedHolidayBase

---

.github/workflows/pre-commit-autoupdate.yml

Tune pre-commit auto-update workflow:
- Remove author (hope this disables the extra trailer)
- Set Python version
- Update name and body

Tune pre-commit auto-update workflow

---

holidays/countries/spain.py
tests/countries/test_spain.py

Update Spain holidays (checked with official sources for 2010-2023).

Update Spain holidays

---

holidays/financial/ny_stock_exchange.py
snapshots/financial/NYSE.json
snapshots/financial/XNYS.json
tests/financial/test_ny_stock_exchange.py

Update NYSE holidays: fix Juneteenth National Independence Day start year (2022 instead of 2021).
Closes #1482.

Update NYSE holidays: fix Juneteenth National Independence Day start year

---

holidays/countries/tanzania.py

This PR implements the `StaticHolidays` method introduced in #1509 for Tanzania (#1505). No other functional changes otherwise.

Implement Tanzania `StaticHolidays` 

---

holidays/countries/bahamas.py

Somehow, the new standard adopted in #1521 wasn't implemented for the Bahamas (we missed it somehow during the PR review) - this PR fixes this.

Remove hard-coding observed_rule for Bahamas

---

holidays/countries/albania.py
holidays/countries/bahamas.py
holidays/countries/cameroon.py
holidays/countries/saudi_arabia.py
holidays/countries/singapore.py
holidays/countries/south_africa.py
holidays/holiday_base.py
holidays/observed_holiday_base.py

Add `special_holidays_observed` support (similar to `special_holidays`, but only works when `self.observed == True`). Relevant holidays in Albania, Bahamas, Cameroon, Saudi Arbia, Singapore, South Africa refactored. In Azerbaijan, case is a bit more complicated.

Add special_holidays_observed support

---

holidays/countries/angola.py
holidays/countries/ecuador.py
holidays/countries/hungary.py
holidays/countries/taiwan.py
holidays/countries/united_states.py
holidays/groups/international.py

Add `_next_year_new_years_day` property to `InternationalHolidays` class. This simplifies observed New Year's Day calculation in countries where observing rules allow for holiday to be moved to **previous** day.

Add `_next_year_new_years_day` to InternationalHolidays

---

holidays/countries/brazil.py

Fix Brazil subdivisions holidays (requesting unsupported categories should return an empty dict now).
This problem was raised in #1559 ("Strange behaviour 3.1"). 

Fix Brazil subdivisions holidays

---

holidays/countries/china.py
tests/countries/test_china.py

A couple of changes in order to make the coverage 100% again. 
I've fixed two cases by changing `elif` to `else` condition and also added non-observed holidays test for one more case. The snapshot generator generates no diff so I hope it should be fine.

Update test coverage to 100%

---

holidays/constants.py
holidays/countries/austria.py
holidays/countries/belgium.py
holidays/countries/brazil.py
holidays/countries/bulgaria.py
holidays/countries/canada.py
holidays/countries/china.py
holidays/countries/denmark.py
holidays/countries/greece.py
holidays/countries/indonesia.py
holidays/countries/israel.py
holidays/countries/japan.py
holidays/countries/laos.py
holidays/countries/liechtenstein.py
holidays/countries/netherlands.py
holidays/countries/portugal.py
holidays/countries/slovakia.py
holidays/countries/south_korea.py
holidays/countries/tanzania.py
holidays/countries/thailand.py
holidays/countries/timor_leste.py
holidays/countries/turkey.py
holidays/countries/uruguay.py
holidays/holiday_base.py
tests/test_holiday_base.py

This PR addresses one of the concerns raised in https://github.com/vacanza/python-holidays/issues/1559
Add supported categories validation:
- Replace set w/ tuple for specifying categories
- Check against entity supported categories instead of all available ones
- Remove `ALL_CATEGORIES` as unused

Add supported categories validation

---

holidays/countries/germany.py

Refactor Germany special holidays (2017 Reformation Day and 75th anniversary of the liberation from Nazism and the end of the Second World War in Europe).

Refactor Germany special holidays

---

RELEASE.rst
scripts/generate_release_notes.py

Use current version for release notes generation

Use current version for release notes generation

---

holidays/countries/portugal.py
tests/countries/test_portugal.py

This aims to fix an issue with the current weekday of the Carnival holiday in Portugal.
It was set to happen on a Monday when it's always been a Tuesday.
There's not an official government document because Carnival is an optional holiday, there is however a Wikipedia [entry](https://pt.wikipedia.org/wiki/Feriados_em_Portugal) with this information.
Closes #1692.
I've ran `make pre-commit` but got the following error message:

Update Portugal: fix Carnival holiday date

---

Makefile

Update `make clean` to take care of docs autosummary

Update make clean action: delete docs autosummary

---

tests/test_registry.py
tests/test_utils.py

Use `assertIsInstance` instead of `assertTrue(isinstance...`)

Update tests: use assertIsInstance

---

holidays/countries/moldova.py
holidays/locale/en_US/LC_MESSAGES/MD.po
holidays/locale/ro/LC_MESSAGES/MD.po
holidays/locale/uk/LC_MESSAGES/MD.po
tests/countries/test_moldova.py

Romanian alphabet use U+0219 (`ș`), not U+015F (`ş`). 

Fix Romanian language strings: replace U+015F with proper U+0219

---

tests/countries/test_united_states.py

Improve `TestUS::test_day_after_thanksgiving` readability.

Update US tests: Day After Thanksgiving

---

README.rst

I've updated the malformed table, the README title and some URL targets. Let's see how it goes from here.

 Fix README layout (attempt 1)

---

holidays/countries/andorra.py
holidays/countries/botswana.py
holidays/countries/honduras.py
holidays/countries/latvia.py

Refactor some sequential holidays (for cleaner code).

Refactor some sequential holidays

---

.github/workflows/ci-cd.yml

Resolves #1777 
This PR addresses the CI/CD issue related to Python versions for the latest macOS image.
Other changes:
- change `actions/setup-python@v5.1.0` to `actions/setup-python@v5`
- add `check-latest: true` for `setup-python` action

 Update CI/CD: fix macOS Python versions

---

holidays/countries/angola.py
holidays/countries/canada.py
holidays/countries/jersey.py
holidays/countries/new_zealand.py
holidays/observed_holiday_base.py
tests/test_observed_holiday_base.py

This PR extends our `ObservedRule` class to support "move to None" cases. In other words it's a holiday removal (no holiday + no observance type of rule). I've got this idea while reviewing https://github.com/vacanza/python-holidays/pull/1792, specifically from [this comment](https://github.com/vacanza/python-holidays/pull/1792/files#r1602976377). It'll be useful for making `IFEU` holiday calendar a bit cleaner.
Let me know your thoughts on this when you get a chance.
P.S. I did my best to avoid naming the rule `???_TO_NONDAY` :)

Update observed rules: add holiday removal support

---

AUTHORS
holidays/registry.py

Perform dynamic imports in registry in dedicated worker thread to avoid deadlocks from concurrent calls to `importlib.import_module` for the same module from different threads.  This may not be sufficient if other code outside of python-holdays is importing these moduels directly.  I believe this cpython issue is related https://bugs.python.org/issue38884.  This should resolve (through a different implementation) #1514.
Here is a flamegraph of the deadlock in action on one thread:
My main concern with this PR is that it may introduce a slight performance degradation.  I'm not sure adding a test will be feasible, as the deadlock is inherently racy.  Making a reliable production in the python-holidays code would require adding a lot of synchronization points within python-holidays to …

Synchronize entity dynamic imports

---

holidays/__init__.py
holidays/deprecation.py
pyproject.toml
tests/countries/test_eswatini.py
tests/countries/test_south_korea.py
tox.ini

This PR adds v1 future incompatibility warning appearing upon `holidays` import. It includes a link to discussion thread to gather ideas and opinions on how to make it as smooth as possible.

Add v1 future incompatibility warning

---

holidays/countries/italy.py

Fix `sphinx.errors.SphinxWarning: /Users/ark/Dev/python-holidays/holidays/countries/italy.py:docstring of holidays.countries.italy.Italy:3:Inline interpreted text or phrase reference start-string without end-string.` error that I was getting locally.

Fix docs: update Italy docstring

---

.github/workflows/ci-cd.yml
.gitignore
Makefile

Migrate to codecov.io

---

.github/workflows/ci-cd.yml

Here I'm trying to improve our CI/CD by not running the jobs twice for PR/commit pushes.

Update CI/CD job concurrency

---

docs/source/examples.rst

Add year and year range example.

Update docs: add years example

---

holidays/holiday_base.py
tests/test_holiday_base.py

Handle `; ` in holidays names.

Extend `HolidayBase::__setitem__` to handle names including `; `

---

.github/workflows/ci-cd.yml
requirements/dev.txt
requirements/docs.txt
requirements/runtime.txt
requirements/tests.txt
tests/test_holiday_base.py

In the first place this PR is aimed to address pypy-3.10 Windows test dependency installation time:
- https://github.com/vacanza/python-holidays/actions/runs/9943738105/job/27468268095#step:4:1
- https://github.com/vacanza/python-holidays/actions/runs/9943156288/job/27466344309#step:4:1
- https://github.com/vacanza/python-holidays/actions/runs/9871369945/job/27259189545#step:4:1
- https://github.com/vacanza/python-holidays/actions/runs/9861241266/job/27229276052#step:4:1
- https://github.com/vacanza/python-holidays/actions/runs/9732827793/job/26859141921#step:4:1
vs
- https://github.com/vacanza/python-holidays/actions/runs/9997135070/job/27633027437#step:4:1
I've pinned pip dependencies to their current versions and removed `--upgrade` pip flags where possible/relevant.
P.S. pypy gave me …

Update CI/CD pip caching

---

README.rst
holidays/countries/__init__.py
holidays/countries/mauritania.py
holidays/registry.py
tests/countries/test_mauritania.py

Add Mauritania holidays

---

.github/workflows/ci-cd.yml

Add documentation build test to CI/CD.

Add documentation build test to CI/CD

---

holidays/countries/singapore.py
tests/countries/test_singapore.py

Added 2025 official holidays for Singapore
Source: Official Government news release at https://www.mom.gov.sg/newsroom/press-releases/2024/0805-public-holidays-for-2025
Testing source: official dates at https://www.mom.gov.sg/employment-practices/public-holidays
- [] I've run `make pre-commit`, it didn't generate any changes
**Not working, but Git runs it automatically**
```
make pre-commit
make: The term 'make' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
- [] I've run `make test`, all tests passed locally
**Not working, but ran it manually from IDE**
```
make test
make: The term 'make' is not recognized as a name of a cmdlet, function, …
```

Update SG: add 2025 official holidays

---

.github/workflows/ci-cd.yml

Update CI/CD: add CodeQL workflow

---

README.rst

The France subdivision is misleading as those are **not** department (as in, sub-area in France mainland) but DOM (département d'outre-mer) or TOM (territoire d'outre-mer):  territories outside of France mainland, more or less administratively connected to France.
I don't know if that matters here, but selecting one should be considered optional as most people would live in France mainland, which is none of those choices.
See https://forum.hacf.fr/t/installer-lintegration-vacances/42799/7

Fix misleading France subdivision

---

.github/workflows/ci-cd.yml
.gitignore
Makefile
requirements/build.txt

This is an PoC version of -sbom.json file generation. For more granular control we should use `cyclonedx-python-lib`.

Implement simple CycloneDX SBOM generation

---

requirements/tests.txt

`numpy v2.1` drops support for Python 3.9; thus, the test requirements need to be updated accordingly.
Resolves #1941 .

Update `numpy` test requirements

---

.github/workflows/ci-cd.yml
tox.ini

Add Python 3.13 (beta) to CI/CD. Final release [expected](https://peps.python.org/pep-0719/) on 2024-10-01.

Add Python 3.13 (beta) to CI/CD

---

README.rst
holidays/countries/bosnia_and_herzegovina.py
tests/countries/test_bosnia_and_herzegovina.py

This PR migrates the Bosnia-Herzegovina's deprecated subdivisions to the new subdivision aliases system.

Migrate deprecated Bosnia-Herzegovina subdivisions to subdivision aliases

---

pyproject.toml

Remove [target-version](https://docs.astral.sh/ruff/settings/#target-version) from tool.ruff.
> If you're already using a pyproject.toml file, we recommend project.requires-python instead, as it's based on Python packaging standards, and will be respected by other tools.

Update pyproject.toml: remove `target-version` from tool.ruff

---

README.rst
holidays/countries/malaysia.py
tests/countries/test_malaysia.py

Restores Malaysia's 3-letter code (previously list as deprecated) as alternative subdivision aliases, as done for Austria's implementation in  #1662 .

Restore Malaysia's 3-letter code as subdivisions aliases

---

README.rst
holidays/countries/isle_of_man.py
holidays/countries/united_kingdom.py
tests/countries/test_united_kingdom.py

This PR migrates the United Kingdom's deprecated subdivisions to the new subdivision aliases system.

Migrate deprecated United Kingdom subdivisions to subdivision aliases

---

holidays/countries/hungary.py
tests/countries/test_hungary.py

Added 2025 Substituted holidays for Hungary according to the NGM ministry.
Added 2025 Substituted holidays for Hungary according to the NGM ministry.

Update HU: add 2025 substituted holidays

---

holidays/countries/australia.py
holidays/countries/cyprus.py
holidays/countries/hongkong.py
holidays/countries/new_zealand.py
holidays/groups/christian.py

Add Easter Tuesday (2 day after Easter Sunday) to Christian holidays group.

Add Easter Tuesday to Christian holidays group

---

docs/source/examples.rst

Update `examples.rst` to reflect last holidays changes.

Update examples to reflect recent holidays changes

---

.pre-commit-config.yaml
holidays/countries/united_states.py
tests/countries/test_united_states.py

Add the Colorado state holiday Francis Xavier Cabrini Day

Add Frances Xavier Cabrini Day for United States, Colorado

---

requirements/tests.txt

Actually bumps [numpy](https://github.com/numpy/numpy) from 2.0.1 to 2.0.2 - now at the correct section of the code. I suspect this will likely remain an issue until Python 3.8's deprecation date sometime this October...
Resolves #2003.

Bump numpy from 2.0.1 to 2.0.2

---

.pre-commit-config.yaml
holidays/calendars/gregorian.py
holidays/calendars/thai.py
holidays/utils.py
scripts/calendar/asian_generator.py
scripts/generate_release_notes.py
tests/common.py
tests/countries/test_finland.py
tests/test_docs.py
tests/test_l10n.py
tests/test_registry.py

This PR switches out [`fix-encoding-pragma`](https://github.com/pre-commit/pre-commit-hooks/pull/1033) hook for [`pyupgrade`](https://github.com/asottile/pyupgrade).
I noticed that the `fix-encoding-pragma` used in `make pre-commit` is listed as deprecated, as seen here:
As written in `pre-commit-hooks` [pypl](https://pypi.org/project/pre-commit-hooks/) page:
> `fix-encoding-pragma`
> Deprecated since py2 is EOL - use [pyupgrade](https://github.com/asottile/pyupgrade) instead.
>
>  Add # -*- coding: utf-8 -*- to the top of python files.
>  To remove the coding pragma pass --remove (useful in a python3-only codebase)

Remove deprecated `fix-encoding-pragma`, add `pyupgrade`

---

.github/CODEOWNERS

I'd like to add @PPsyrius to the CODEOWNERS file to appreciate and encourage continuous contributions to the `holidays` code base.

Add @PPsyrius to CODEOWNERS

---

AUTHORS
README.rst
holidays/countries/vietnam.py
holidays/locale/en_US/LC_MESSAGES/VN.po
holidays/locale/vi/LC_MESSAGES/VN.po
tests/countries/test_vietnam.py

Add `vi` translation of Vietnam holidays.
This translation has been checked by me who was born and currently lives in Viet Nam and crossed-checked with the state [source](https://hethongphapluat.com/bo-luat-lao-dong-2019/dieu-112).

Add Vietnamese translation of VietNam holidays

---

.pre-commit-config.yaml
holidays/groups/buddhist.py
holidays/groups/chinese.py
holidays/groups/hindu.py

Based on https://github.com/vacanza/holidays/actions/runs/11356900938
I'm not really sure if it's the best way to address it. Feel free to suggest better options if you see any.

Satisfy mypy requirements

---

holidays/countries/united_states.py
tests/countries/test_united_states.py

According to the ["Alaska Dispatch"](https://web.archive.org/web/20120502232826/http://www.alaskadispatch.com/article/happy-alaska-day-great-land):
> The changing of the colors and the guard is commemorated in Alaska each Oct. 18, designated "Alaska Day," an official state holiday in 1917 by the third Territorial Legislature. That same year, territorial lawmakers also created Seward's Day, also a state holiday, to mark on each final Monday in March the signing of the purchase treaty.
Thus, the start date for this should be 1917 instead of 1867 as in the current implementation.
As for `Seward's Day`, a local newspaper mentioned that [this wasn't observed in 1921](https://chroniclingamerica.loc.gov/lccn/sn86072239/1922-03-29/ed-1/seq-8/):
> [!NOTE]
> There's currently 2 state-level checks …

Update United States holidays: Alaska state holidays correction

---

holidays/countries/cambodia.py
tests/calendars/test_thai.py
tests/countries/test_cambodia.py
tests/countries/test_laos.py

As proposed by @KJhellico in #2081 :
> Now that 2058 is no longer a special year for Thai calendar, can we replace it with a more standard 2050? Or rather, 2049, because most countries use range(N, 2050).
> I think the checks for 2158 are more related to Thai calendar tests than to Thailand itself. And since `tests\calendars\test_thai.py` already contains checks for this year, they are redundant here.
This PR aims to address these issues.
- Switching test case end date back to 2050 like other typical country-level implementations.
- Moving all relevant Thai calendar-related testing to Thai calendar test cases, except for `Pchum Ben` and `Bon Om Tok` since we'll still need to check for its 2-day and 3-day celebration variants.
[contributing-guidelines]: …

Refactor Cambodia and Laos test cases

---

holidays/countries/thailand.py

Further fix for #2081 so `make l10n` command no longer removes the translation comment from Asarnha Bucha localization entry.

Fix `make l10n` removing loc comment for Asarnha Bucha

---

holidays/countries/germany.py
holidays/locale/de/LC_MESSAGES/DE.po
holidays/locale/en_US/LC_MESSAGES/DE.po
holidays/locale/th/LC_MESSAGES/DE.po
holidays/locale/uk/LC_MESSAGES/DE.po
snapshots/countries/DE_BE.json
tests/countries/test_germany.py

Adds the `75th anniversary of the East German uprising of 1953` for Berlin, Germany in 2028. English localization is partially based on a [DW article](https://www.dw.com/en/berlin-commemorates-1953-uprising-in-east-germany/a-39289423) and Ukranian one could use a review here @KJhellico .
Resolves #2089 .

Update Germany holidays: add East German Uprising Day 2028 in Berlin

---

tests/countries/test_australia.py

Refactor Australia tests

---

scripts/l10n/generate_po_files.py

Add financial markets l10n support to `generate_po_files.py` script.

Add financial markets l10n support

---

holidays/countries/switzerland.py
holidays/locale/de/LC_MESSAGES/CH.po
holidays/locale/en_US/LC_MESSAGES/CH.po
holidays/locale/fr/LC_MESSAGES/CH.po
holidays/locale/it/LC_MESSAGES/CH.po
holidays/locale/uk/LC_MESSAGES/CH.po
tests/countries/test_switzerland.py

Like in other German speaking countries, January 01 is called "Neujahr" in Switzerland, not "Neujahrestag". "Neujahr*e*stag" would be wrong anyway, it would be "Neujahrstag".

Update CH holidays: rename Neujahrestag to Neujahrstag

---

holidays/countries/canada.py
tests/countries/test_canada.py

Update CA holidays: Nunavut Day is NU public holiday since 2020 (was `OPTIONAL` in 2000-2019).

Update CA holidays: Nunavut Day is NU public holiday since 2020

---

holidays/countries/timor_leste.py
snapshots/countries/TL_COMMON.json
tests/countries/test_timor_leste.py

Add an additional day off on 29 November, 2024 for Timor Leste on the occasion of [the 49th Anniversary of the Proclamation of Independence of Timor-Leste](https://timor-leste.gov.tl/?p=40955&lang=pt)

Update Timor Leste holidays: Add 2024 Nov 29 Special Holiday

---

holidays/countries/finland.py
tests/countries/test_finland.py

Fixing Finland's Independence Day appearing pre-1917, also standardized the test cases end date to 2049 as other entries.

Update Finland holidays: fix Independence Day appearing pre-1917

---

README.rst
holidays/countries/france.py

I had to look up in the source code what MQ, RE... meant. The README didn't help either, just listing the raw codes available.
Those are not of common use in the French culture, contrary to say, AZ meaning Arizona in the US culture.
Also fixed the official spelling.
## Additional notes
For the record, it started with me adding a holiday calendar in my Home Assistant. I was left puzzled with that list:
And when I couldn't find the meaning of those abbreviations in the documentation either, I thought it was time to contribute.
The next step is to get in touch with the maintainers of this Home Assistant integration, and ask them to use the …

Add French subdivision aliases

---

holidays/countries/kazakhstan.py
snapshots/countries/KZ_COMMON.json
tests/countries/test_kazakhstan.py

Update KZ holidays: add 2025 special and substituted holidays.

Update KZ holidays: add 2025 special holidays

---

.github/workflows/ci-cd.yml

Add signed artifacts path

---

holidays/countries/south_korea.py
snapshots/countries/KR_COMMON.json
tests/countries/test_south_korea.py

Add South Korea's temporary public holidays to [January 27th, 2025.](https://biz.chosun.com/en/en-policy/2025/01/07/IJUARF6LM5DBJPGYGGXRYGM7X4/)
Your PR description goes here.

Update South Korea holidays: 2025 temporary public holidays

---

holidays/holiday_base.py

Add faster date parsing from strings in ISO 8601 format ("YYYY-MM-DD" or "YYYYMMDD"): use `date.fromisoformat()` instead of `dateutil.parser.parse()`.
Speed comparison:
```shell
python -m timeit -s "from dateutil.parser import parse" -n 100000 "d = parse('2024-12-25')"
100000 loops, best of 5: 20.7 usec per loop
python -m timeit -s "from datetime import date" -n 10000 "d = date.fromisoformat('2024-12-25')"
10000 loops, best of 5: 127 nsec per loop
```

Add faster date parsing from strings in ISO 8601 format

---

AUTHORS
tests/test_utils.py

Now that `.po` files are no longer included in distribution bundles (https://github.com/vacanza/holidays/pull/2243), having this test look at `.po` files makes things slightly more difficult for downstream distributors such as Debian, since we run the tests on the equivalent of the built wheel.

Check .mo rather than .po files in TestListLocalizedEntities

---

.gitattributes
.pre-commit-config.yaml
make.cmd

Add CMD script for Windows with `make`-like functionality.

Add make script for Windows

---

holidays/locale/th/LC_MESSAGES/HK.po

Fixing `th` l10n typo for Hong Kong.

Update Hong Kong holidays: fix `th` l10n typo

---

holidays/countries/philippines.py
tests/countries/test_philippines.py

Adjust the Philippines holiday Bonifacio Day for 2023. 
Bonifacio Day was moved from 2023-11-30 to 2023-11-27.
Source:
https://www.officialgazette.gov.ph/2022/11/09/proclamation-no-90-s-2022/

Update Philippines holidays:  adjust Bonifacio Day for 2023

---

.github/workflows/ci-cd.yml
.github/workflows/pre-commit-autoupdate.yml
.github/workflows/prl-labeler.yml
.github/workflows/update-snapshots.yml
CONTRIBUTING.md

Closes: #2343 
Added commit SHAs instead of versions in workflow files.

Added commit SHAs instead of versions

---

holidays/countries/singapore.py
snapshots/countries/SG_COMMON.json
tests/countries/test_singapore.py

- Add Singapore's 2025 polling day.
- Update special holidays sources from 2020 onwards to use the https://mom.gov.sg source.
- Add every special holiday entry to `test_special_holiday` .
Resolves #2486.

Update Singapore holidays: 2025 Polling Day on May 3rd

---

holidays/countries/argentina.py
holidays/locale/en_US/LC_MESSAGES/AR.po
holidays/locale/es/LC_MESSAGES/AR.po
holidays/locale/uk/LC_MESSAGES/AR.po
snapshots/countries/AR_B.json
tests/countries/test_argentina.py

Adds November 30, 2018, as a one-off public holiday in Buenos Aires for the G20 Leaders' Summit.
Resolves #2528.

Update Argentina holidays: add 2018 G20 Leaders' Summit for Buenos Aires

---

holidays/countries/svalbard_and_jan_mayen.py

[As raised by](https://github.com/vacanza/holidays/pull/2642#discussion_r2154215813) @coderabbitai for PR #2642.
> **You redefine `supported_languages`; risk of future drift.**
> Parent entities already maintains its own tuple.  If a new language is later added upstream, `HolidaysXX` will silently miss it.
> Keeps things DRY.  
Since Svalbard and Jan Mayen use the same `default_language` as Norway, there's no need to keep a separate list unlike the Åland Islands (which I'm getting back to finish implementing that l10n feature soon)

Update Svalbard and Jan Mayen holidays: remove l10n overrides

---

CONTRIBUTING.md
Makefile
make.cmd

Retire `make coverage`, extend `make test` to show uncovered lines by default.

Show test coverage details by default
