README.rst
holidays.py
tests.py

according article from Wikipedia (https://de.wikipedia.org/wiki/Feiertage_in_%C3%96sterreich)

add holidays for Austria

---

.gitignore
holidays.py

Working mostly from this list from the CRA -- http://www.cra-arc.gc.ca/tx/hldys/menu-eng.html -- and details from Wikipedia

Update Canadian Holidays

---

holidays.py
tests.py

Adding Extended Days that most people have as a bonus from their
company's or that take from the vacation days for theirselves

Adding PT Holidays

---

README.rst
holidays.py
tests.py

Based on gablank's code for Norwegian holidays

Add Swedish holidays

---

holidays.py
tests.py

Hi @ryanss!
I've added Japanese holidays and their tests.

Add Japanese holidays

---

README.rst
holidays.py
tests.py

Because nothing had been done for pull request #44 since late March, I have made changes according to the comments. I have also reviewed the holidays and removed days that are work free according to Swedish vacation laws but not actual holidays according to holiday law [1989-253](http://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-1989253-om-allmanna-helgdagar_sfs-1989-253)

Adjusted pull request Swedish holidays (#44) by @johanpalmqvist according to Swedish holiday laws and comments.

---

.travis.yml
README.rst
holidays.py
tests.py

Hi!
I've added Slovenian national holidays that are work-free and corresponding tests.
BR!

Add Slovenian national holidays

---

holidays.py

fix issue #75 
October Bank Holiday in Ireland is wrong

fix Ireland Oct. bank holiday

---

MANIFEST.in

This PR adds changelog into pypi tarball, which I'm using for Debian package.
Thanks.

Add CHANGES into pypi tarball

---

README.rst
holidays.py
tests.py

Feature argentina holidays

---

README.rst
holidays.py
tests.py

Added Hungarian Holidays

---

README.rst
holidays.py
tests.py

States holidays and all national holidays of India added.

Added Country INDIA holidays

---

CHANGES
holidays.py
tests.py

I need to provide unit test coverage for this, but I opened the PR already to keep track of it!
Thanks for the module!

Support for Brazilian holidays

---

holidays.py

Reverts dr-prodigy/python-holidays#150. Pull request will be merged to beta, then merged on master at next lib release.

Revert "Revert 'additional German provinces got "Reformationstag"'. Added holidays twice."

---

README.rst
holidays.py
tests.py

Support for Lithuanian holidays.
This is my first pull request.

Lithuanian holidays support

---

holidays.py
tests.py

Pres Ramaphosa announced election day 2019 to be 8th May in State of Nation Address last night

Election Day 2019

---

README.rst
holidays.py
tests.py

Thank you for maintaining this nice and useful module!

Support for Bulgaria's official holidays

---

holidays.py
tests.py

- Add new holidays regarding the ceremonies of the new Emperor in Japan

Add Japanese holidays on the new Emperor

---

holidays.py
tests.py

* Added new entry of Estonian holidays into the library

Add support for Estonian public holidays

---

README.rst
holidays.py
tests.py

Edit: Full disclosure: I'm a complete noob developer. :smiley:

Added the official holidays of Aruba

---

holidays.py
tests.py

I have revised the pull request #208 and fixed the following issues.  Please take a look of it. Thanks. 
- Switched the base branch to beta
- Fixed PEP-8 issue
- Tests were grouped and reorganised

Add support for hongkong (revised)

---

holidays.py
tests.py

Public holiday in canton of Vaud.

Add Lundi du Jeûne Switzerland holiday

---

README.rst
holidays.py
tests.py

Add support for Peru. The user "madralino" that commit the change is also mine. Any problem or sugestion with the code, don't doubt to tell me.

Add support for Peru

---

holidays.py
tests.py

Not sure where the test coverage results should be stored. But here are the results
Test coverage:
```
Name          Stmts   Miss  Cover   Missing
-------------------------------------------
holidays.py    2893      9    99%   3726-3727, 3729, 3733, 3735, 3737, 3739-3740, 3742
tests.py       3889      0   100%
-------------------------------------------
TOTAL          6782      9    99
```

ensures that specified year is returned for special dates

---

README.rst
holidays.py
tests.py

Adds support for fixed holidays in Nigeria

Support nigeria

---

holidays.py

Added Telangana state(TS) and its holidays.

Telangana State (TS ) was added

---

tests.py

Fix tests in 2020
This Fixes #234
This PR was done while working on reproducible builds for openSUSE.

Fix tests in 2020

---

holidays.py
tests.py

I made some fixes and add holidays for Chile. For my changes the coverage report is fine but for line 1000. I couldn't fix the tests failing for India.
```bash
coverage report -m
Name          Stmts   Miss  Cover   Missing
-------------------------------------------
holidays.py    2949     26    99%   1000, 4311-4313, 4316, 4319-4320, 4323-4324, 4329, 4332-4333, 4336-4338, 4341, 4344, 4347, 4350, 4353, 4356, 4359, 4362, 4365,
4370-4371
tests.py       3943     53    99%   4628-4682
-------------------------------------------
TOTAL          6892     79    99%
```

Add Chile. Fix tests

---

README.rst
holidays.py
tests.py

Base on:
Judgment No. 14 of Feb 20, 2008 of the Supreme Court of Justice
Law No. 139-97 - Holidays Dominican Republic - Jun 27, 1997

Add Dominican Republic Holidays

---

README.rst
holidays.py
tests.py

Hi, i add Holidays for Nicaragua

add Nicaragua holidays

---

.gitignore
holidays.py
tests.py

Hi, this is my first contribution. Trying to add support for Serbia holidays.

Add support for Serbia holidays

---

README.rst
holidays.py
tests.py

Hello!
This is a pull request to add support for Greek holidays.

Added support for Greece.

---

holidays.py

Hi, this is my first constribution in a open source library. I have more latin conutries to add, but i want to know if this contribution is okay in order to made the other countries.
Thanks

Adding Paraguay public holidays support

---

holidays/countries/spain.py

CAM has holiday "San José", "Lunes de Pascua"
CVA has "San Juan" and not has "Jueves Santo"

Fix Spanish Holidays

---

holidays/countries/mexico.py
tests.py

source of information was
* [Holidays and Observances in Mexico in 2020](https://www.timeanddate.com/holidays/mexico/)
* [Holidays in Mexico](https://publicholidays.mx/)
tests are all passing
Signed-off-by: Rosi2143 <Schrott.Micha@web.de>

Adding/correcting holidays for mexico.

---

holidays/countries/portugal.py

A few of the strings were misspelled and "Christmas Day" was still in English.

Corrected some misspellings and one string that was still in English

---

holidays/countries/__init__.py
holidays/countries/korea.py
tests.py

Copied from HongKong Holidays for Lunar calculation function.
- Added Tests for each holidays
- Works until 2099.

Add support for Korea holidays

---

README.rst
holidays/countries/__init__.py
holidays/countries/egypt.py
holidays/countries/morocco.py
tests.py

- Support for Moroccan Holidays.
- Fixed small typo in Egypt Holidays.

Support for Morocco Holidays

---

README.rst
holidays/countries/__init__.py
holidays/countries/burundi.py
tests.py

Hi, this is my first contribution. Trying to add support for the Burundian holidays.

Add support for Burundian holidays

---

README.rst
holidays/countries/__init__.py
holidays/countries/latvia.py
tests.py

Holidays in Latvia

---

CHANGES
README.rst
holidays/countries/__init__.py
holidays/countries/romania.py
tests.py

This PR just add Romania support.
Thank you for your work.

Add Romania support

---

holidays/countries/germany.py
tests.py

I added BYP for Bavaria with more protestants than catholic.
This package is used by home assistance for house automation. With this change it is possible to get woken up on Maria Himmelfahrt, so I can go to work

Update germany.py -  Added PROVINCES BYP

---

holidays/countries/__init__.py
holidays/countries/united_arab_emirates.py
tests.py

Hi @dr-prodigy , took a shoot at adding holidays for UAE after reviewing official calendars for the last 5-6 years. Apart from the usual issues with the islamic calendar, the tests proved accurate.
The UAE government also seems to extend public holidays duration arbitrarily by 1 or 2 days depending on the year, this is not something I implemented, would be a best guess situation.
Feel free to let me know if anything with this needs fixing, I hope this can be of help :-)
Cheers

Add UAE holidays

---

holidays/countries/croatia.py
tests.py

Resolves #369 
Based on public law 022-03 / 19-01 / 219 of 14 November 2019 https://narodne-novine.nn.hr/clanci/sluzbeni/2019_11_110_2212.html (Google Translate at https://translate.google.com/translate?sl=hr&tl=en&u=https%3A%2F%2Fnarodne-novine.nn.hr%2Fclanci%2Fsluzbeni%2F2019_11_110_2212.html )

Croatia updates

---

README.rst
holidays/countries/chile.py
tests.py

Implemented all known laws and documented them.
Addressed all issues in #328

Cleaned up Chile

---

holidays/holiday_base.py

Fix pop_named() sometimes generates an exception

---

holidays/countries/mexico.py

Fix 3 x Benito Juarez's Birthday in 2021

---

tests.py

Makes submitting clean(er) code easier

Add flake8 to unittests

---

holidays/countries/spain.py
tests.py

This PR finalizes #310
Sorry @dr-prodigy, I were so busy in that date. I hope you are OK with this PR :-)

Spain sunday holidays to monday

---

holidays/holiday_base.py
tests.py

Disable year expansion on name search 

---

.travis.yml
holidays/countries/israel.py
setup.py

convertdate API changed and broke IsraelHolidays class
This PR solves the integration issues and reported issues #406 #391

support new convertdate version

---

README.rst
holidays/countries/__init__.py
holidays/countries/saudi_arabia.py
tests.py

For holidays in Saudi Arabia reference:
https://laboreducation.hrsd.gov.sa/en/gallery/274

Add Saudi Arabia

---

holidays/countries/__init__.py
holidays/countries/curacao.py
tests.py

Hi,
First pull request. Hopefully all requirements are met to add Curaçao holidays to the list.
Regards,
Raychel

Add Curacao holidays

---

holidays/countries/israel.py
test/countries/test_israel.py

Fixed bug in Purim holiday + adding tests for Purim

Fixed bug in Israel Holidays

---

CHANGES
README.rst
holidays/countries/__init__.py
holidays/countries/jamaica.py
tests.py

Hi,
I added Jamaica holidays.
Thank you,
Edison

Added Jamaica holidays

---

holidays/countries/__init__.py
holidays/countries/georgia.py
tests.py

I add Georgian holidays and updated tests correspondingly.
Fixes #434

Add Georgian holidays

---

holidays/countries/singapore.py

Fix for multi-year query

---

holidays/holiday_base.py
test/test_holiday_base.py

fixed holidays pickling

---

.gitignore

Just passing by, noticed this was wrong :)

Fix bad merge

---

holidays/countries/poland.py
test/countries/test_poland.py

On 2018-11-12 there was special holiday due
to 100th annviersary of Independence Day

Missing Polish bank holiday added

---

holidays/countries/venezuela.py
test/countries/test_venezuela.py

I add the venezuela.py file, but still don't know how to change the rest of the files for it to load with holidays.py. I use Colombia and Brazil as a guide.

Adding Venezuela to the list

---

README.rst
holidays/countries/__init__.py
holidays/countries/malaysia.py
test/countries/test_malaysia.py

The following holidays still need to be added 
- Isra and Miraj in Malaysia
- NUZUL AL-QUARAN DAY
- The Sultan of Pahang Hol in Pahang
- Birthday of SPB Yang di Pertuan Agong
- Birthday of the Sultan of Kedah in Kedah
- Birthday of the Raja of Perlis
- Hijri New Year Awal Muharram or Maal Hijrah
- The Sultan of Johor Hol
- Muhammad's Birthday
The following holidays are hardcoded and must be changed 
- Thaipusam Holiday

Add Malaysian holidays

---

README.rst
holidays/countries/__init__.py
holidays/countries/zambia.py
test/countries/__init__.py
test/countries/test_zambia.py

Support for Zambia

---

holidays/countries/angola.py
holidays/countries/united_states.py
test/countries/test_angola.py

This PR removes duplicated holidays in two countries:
- USA : Juneteenth National Independence Day(Jun 19th)
- Angola : Dia do Heroi Nacional (Sep 17th)
This PR should close #505 and fix #488

Remove duplicated Holidays 

---

holidays/countries/bulgaria.py
test/countries/test_bulgaria.py

I tried to added missied dates to bulgaria.py as noted in [https://github.com/dr-prodigy/python-holidays/issues/507](url) 
I hope it will work.

missed dates added on Bulgaria

---

README.rst
holidays/countries/__init__.py
holidays/countries/china.py
test/countries/test_china.py

Information about holidays is taken from here https://en.wikipedia.org/wiki/Public_holidays_in_China
The most complicated and confusing holiday is Tomb-Sweeping Day which can be on 4, 5 or 6 April. It happens  `on the15th day after the Spring Equinox`.  Spring Equinox is on March 20 but Tomb-Sweeping Day varies. Maybe Chinese define it in a different way.
Hardcode Tomb-Sweeping Day was not an option because different source conflicts and provide different dates
So i considered it happens on every April 5.

Adding China

---

holidays/holiday_base.py

Spelling and grammar update. Excuse my OCD.

Grammatical changes in docs

---

holidays/countries/__init__.py
holidays/countries/kazakhstan.py
test/countries/test_kazakhstan.py
tests.py

I made an earlier PR on this but left it get stale, so here's another go at adding Kazakh holidays to the package. The tests run ok this time, and all pre-commit checks pass. I still haven't worked through each holiday to account for observance of days that fall on weekends, but getting the list of holidays in would already be helpful for me and mean I can move an internal tool from using my fork to running directly on upstream

Add holidays for Kazakhstan

---

holidays/countries/india.py

Sup doc,
Guess you are busy with real life stuff so took the privilege to make a few changes without waiting for your reply which I feel are in the right direction based on available data. Detailed changes:
- Updated borked calendarlab link and added new references for changes done
- Missing states and union territories added to list
- Sorted state list by status first and then alphabetically (UT's at the bottom)
- Full state names in comments along side state codes
- State code for Odisha changed to "OR" as used in govt websites
- Added Diwali and Holi from FBProphet as requested in #538 (only for India)
- Added warnings regarding year range for Diwali and Holi as in FBProphet

Added missing states and two major holidays

---

README.rst
holidays/countries/__init__.py
holidays/countries/taiwan.py
test/countries/test_taiwan.py

I have added the public holidays of Taiwan.

Add public holidays of Taiwan

---

holidays/countries/colombia.py

Revert "Update colombian holidays"

---

holidays/countries/venezuela.py
test/countries/test_venezuela.py

Hi, I missed "Muerte del Libertador Simón Bolívar" when I wrote the holidays for Venezuela, I added them this time

Added a missing Holiday to Venezuela

---

holidays/holiday_base.py
holidays/utils.py

Fix errors with type hints

---

holidays/countries/united_kingdom.py

This line would Error out when `state` is `None`.

Issue with state=None in United Kingdom

---

README.rst
holidays/countries/spain.py
test/countries/test_spain.py

* Added Ceuta autonomous city as CE.
* Added local festivities of Melilla (not sure if ML is Melilla, the 2 letter abbreviation is confusing for us; Spanish people).
* Reordered some ifs and arrays to respect alphabetical order.
* Fixed typo with `País Vasco`.
* Not sure why in some strings the province is separated between "" so I did it with all because is due to any future translation.
I am not sure why test are not passing locally on my machine
Melilla local festivities normally are two more important muslims festivities so I add them as it is in Morocco library but.
I made in other branch this changes and some 2022 exceptions but not sure if 2022 changes must be in other branch. So I will add them after this will be approval because I also have to know a little bit about python to …

[Feature] spain adds ceuta

---

.github/workflows/ci-cd.yml

Reverts dr-prodigy/python-holidays#599

Revert "Bump pypa/gh-action-pypi-publish from 1.4.2 to 1.5.0"

---

holidays/countries/uzbekistan.py
test/countries/test_uzbekistan.py

Added Uzbekistan holidays. Please approve

Uzbekistan holidays (+ tests)

---

docs/source/index.rst

Fix detritus from bad merge (not mine!) preventing correct building of docs

Fixed docs

---

holidays/countries/spain.py
test/countries/test_spain.py

I've fixed Valencia and Aragón holidays.

Update Spain holidays

---

docs/requirements.txt

Fix for readthedocs.io_build

---

README.rst
holidays/countries/__init__.py
holidays/countries/malta.py
test/countries/test_malta.py

Malta holidays (+ tests)

---

.pre-commit-config.yaml
README.rst
holidays/countries/__init__.py
holidays/countries/cyprus.py
test/countries/test_cyprus.py

Adds the public holidays for Cyprus; fixes #410.

Cyprus holidays

---

holidays/countries/morocco.py
holidays/countries/nigeria.py
holidays/countries/united_kingdom.py
holidays/holiday_base.py
holidays/utils.py

- Tighten up the typechecking on HolidayBase
- ditto holidays.utils
- then I did the UK, because it's nearby
- then I picked off a couple of the more egregious warnings where the same function was defined twice
- then I'd had enough, I certainly don't intend to go through every country...

Typechecking

---

holidays/countries/italy.py

source: https://it.wikipedia.org/wiki/Pentecoste

added pentecost monday for province of bolzano

---

holidays/countries/cuba.py

Fix typo in comment for Cuba

---

holidays/countries/honduras.py
test/countries/test_honduras.py

Honduras had weird behavior with self.observed and did not follow the Morazan Weekend correctly since it is the first week of October from wednesday to friday (technically noon wednesday to noon saturday).

Fix honduras

---

README.rst

README.rst: Fix documentation about Portugal subdiv param

---

holidays/countries/honduras.py
test/countries/test_honduras.py

Add test for 2025 to cover this case (when Oct 1st is the first Wed of the month)

Fix Honduras Morazan weekend bug.

---

holidays/countries/ukraine.py

Update Day of the defenders of Ukraine name
Update Christmases names
Fix some names orthography

Update Ukrainian holidays

---

holidays/countries/ukraine.py
test/countries/test_ukraine.py

Added observed holidays for Ukraine and tests (last years and full for observed dates)

Added observed holidays for Ukraine

---

holidays/countries/singapore.py
test/countries/test_singapore.py

Fix Singapore Diwali date for 2022.

---

holidays/countries/ukraine.py

Make observed holidays calculation more universal and readable

Ukraine: optimizations

---

test/countries/test_ireland.py

Clean up test_ireland.py.

---

docs/source/examples.rst
holidays/holiday_base.py

Code comments (and example) per #704

Add documentation to _populate (see #704)

---

.pre-commit-config.yaml
holidays/countries/hongkong.py
test/countries/test_hongkong.py

Added special case on 2022 Chinese Mid-Autumn Festival
Added test case on test_hongkong.py
Run tox and passed pre-commit

Added special case on 2022 Hong Kong

---

holidays/countries/norway.py
holidays/countries/sweden.py
test/countries/base.py
test/countries/test_norway.py
test/countries/test_sweden.py

- Remove `assert`s
- Rework all Sundays collection logic (use dateutil.rrule). 
- Extract repetitive test_sundays code to a separate file.

Rework Norway and Sweden logic.

---

holidays/countries/south_africa.py
test/countries/test_south_africa.py

- replace while loops with dateutil logic (#768)
- Queen's Birthday day fix
- observed holidays calculation fix (#727)
- added tests

South Africa: updates

---

test/countries/test_israel.py
test/countries/test_malaysia.py
test/countries/test_spain.py
test/test_holiday_base.py

Migrate `assert` from holidays/ to test/

Replace Python built-in asserts with unittest asserts.

---

.pre-commit-config.yaml
holidays/countries/hongkong.py
holidays/countries/malaysia.py
holidays/countries/singapore.py
test/countries/test_hongkong.py

#778 correct rules of mid_autumn which lies on Saturday before and after 2011 
Added test case on test_hongkong.py
Run tox and pass pre-commit

Update Hong Kong holiday

---

holidays/countries/sweden.py
test/countries/test_sweden.py

- Midsummer evening fix (#731 by @sander-visser)
- test added

Sweden: fix Midsummer evening

---

holidays/countries/eswatini.py
test/countries/test_eswatini.py

Swaziland deprecation warning

---

.pre-commit-config.yaml
holidays/countries/hongkong.py
test/countries/test_hongkong.py

- holidays establishing years specified
- historical holidays added
- Lunar New Year and Christmas calculation fix
- Ching Ming Festival / Easter Monday overlapping fix
- optimizations
- tests added

Hong Kong holidays update

---

README.rst
holidays/countries/__init__.py
holidays/countries/indonesia.py
test/countries/test_indonesia.py

Added Indonesian holidays

---

holidays/countries/korea.py
test/countries/test_korea.py

Fix for Tree planting day #788, Labour day #789, Hangeul day #790

Korea: fixed holidays relevance period

---

.pre-commit-config.yaml
holidays/countries/bulgaria.py
holidays/countries/czechia.py
holidays/countries/djibouti.py
holidays/countries/hongkong.py
holidays/countries/norway.py
holidays/countries/poland.py
holidays/countries/singapore.py
holidays/countries/slovakia.py
holidays/countries/tunisia.py
holidays/countries/vietnam.py
holidays/holiday_base.py
setup.cfg
test/countries/test_czechia.py
test/countries/test_india.py
test/countries/test_malta.py
test/countries/test_poland.py
test/countries/test_slovakia.py
test/countries/test_spain.py

Implement flake8 suggested fixes:
- Fine tune flake8 setup.cfg config.
- Remove unused imports.
- Add __init__.py to test/financial.
- Add flake8-print.

Clean up unused imports.

---

.pre-commit-config.yaml
README.rst
setup.cfg

Clean up .pre-commit-config.yaml.

---

holidays/countries/malaysia.py
test/countries/test_malaysia.py

- fixed dates of some islamic and lunisolar calendar holidays
- rewritten observed calculation (by states)
- huge refactoring
- rewritten tests

Malaysia large update

---

holidays/countries/nigeria.py
test/countries/test_nigeria.py

- observed holidays calculation fix
- added missing Mawlid holiday

Nigeria holidays update

---

holidays/countries/paraguay.py
test/countries/test_paraguay.py

- added special holidays
- fixed observance calculation

Paraguay holidays update

---

holidays/countries/chile.py
holidays/utils.py
test/countries/test_chile.py

Fix the holiday day when year > 2021 according to the calculated solstice datetime adjusted to Chile timezone UTC-3 
Added necessary util Class _AstroMeeusAlgorithms
Issue: https://github.com/dr-prodigy/python-holidays/issues/666

chile: Día Nacional de los Pueblos Indígenas

---

holidays/countries/kazakhstan.py
test/countries/test_kazakhstan.py

- observed holidays
- holidays relevance period

Kazakhstan update

---

holidays/countries/kazakhstan.py
test/countries/test_kazakhstan.py

Reverts dr-prodigy/python-holidays#829

Revert "Kazakhstan update"

---

test/common.py

Fix `TestCase::parse_arguments` instance determining logic.

---

holidays/countries/kazakhstan.py
test/countries/test_kazakhstan.py

Reverts dr-prodigy/python-holidays#842

Reapply "Kazakhstan update"

---

holidays/countries/chile.py
test/countries/test_chile.py

- holidays relevance period fixes
- historical holidays added
- special holidays added
- tests for all holidays

Chile large update

---

README.rst
holidays/countries/__init__.py
holidays/countries/pakistan.py
test/countries/test_pakistan.py

Added Pakistan holidays

---

holidays/utils.py
test/test_utils.py

Added tests for _AstroMeeusAlgorithms

---

holidays/countries/united_states.py
test/countries/test_united_states.py

- Truman Day, Inauguration Day, Evacuation Day observation fixed
- optimizations

United States update

---

holidays/countries/__init__.py
holidays/countries/moldova.py
holidays/holiday_base.py
holidays/utils.py
setup.cfg
test/test_imports.py

Reconfigure holidays imports:
* Unify top level imports style
* Limit imports for holiday_base and utils
* Reorder country imports
* Add Moldova alpha-3 code
* Add tests

Refactor imports

---

holidays/countries/azerbaijan.py
requirements_dev.txt
test/countries/test_azerbaijan.py

- update holidays
- observed dates calculation completely rewritten

Azerbaijan large update

---

.pre-commit-config.yaml
tox.ini

- Disable test coverage when tests fail
- Enable pre-commit automatic update
- Reformat tox.ini

Update tox configuration

---

holidays/countries/singapore.py
test/countries/test_singapore.py

- observed holidays calculation fixed
- some holidays dates fixed

Singapore holidays update

---

holidays/countries/aruba.py
holidays/countries/curacao.py
holidays/countries/netherlands.py
holidays/countries/south_korea.py

Use augmented assignment statements

---

test/countries/test_argentina.py
test/countries/test_australia.py
test/countries/test_austria.py
test/countries/test_bulgaria.py
test/countries/test_canada.py
test/countries/test_colombia.py
test/countries/test_cuba.py
test/countries/test_ireland.py
test/countries/test_israel.py
test/countries/test_mexico.py
test/countries/test_new_zealand.py
test/countries/test_paraguay.py
test/countries/test_united_kingdom.py
test/countries/test_united_states.py
test/countries/test_uruguay.py
test/countries/test_venezuela.py
test/countries/test_vietnam.py
test/financial/test_european_central_bank.py
test/financial/test_ny_stock_exchange.py

- Standardize `relativedelta` days usage
- Replace `timedelta` with `relativedelta`

Clean up timedelta/relativedelta usage (tests)

---

.pre-commit-config.yaml
holidays/countries/armenia.py
holidays/countries/australia.py
holidays/countries/bosnia_and_herzegovina.py
holidays/countries/chile.py
holidays/countries/djibouti.py
holidays/countries/egypt.py
holidays/countries/estonia.py
holidays/countries/ethiopia.py
holidays/countries/germany.py
holidays/countries/israel.py
holidays/countries/italy.py
holidays/countries/malaysia.py
holidays/countries/mexico.py
holidays/countries/new_zealand.py
holidays/countries/singapore.py
holidays/countries/united_arab_emirates.py
holidays/countries/zambia.py
test/countries/test_bosnia_and_herzegovina.py
test/countries/test_cyprus.py
test/countries/test_greece.py
test/countries/test_spain.py
test/countries/test_united_states.py

The changes have been generated automatically by pre-commit.

Upgrade dependency: change black version from 22.12.0 to 23.1.0

---

README.rst
holidays/countries/__init__.py
holidays/countries/panama.py
test/countries/test_panama.py

Add Panama holidays

---

test/common.py
test/countries/test_bolivia.py
test/countries/test_chile.py
test/countries/test_jamaica.py
test/countries/test_panama.py

Change some of common.TestCase methods behavior:
- `TestCase::assertHolidayName`
- `TestCase::assertHolidaysName`
- `TestCase::assertNoHolidayName`

Refactor common.TestCase

---

holidays/countries/australia.py
test/countries/test_australia.py

Update Australia holidays: fix 2020 QLD holidays

---

holidays/countries/hongkong.py

Redundant code remained from complex merge, as I understand.

Fix Hong Kong

---

README.rst
holidays/countries/__init__.py
holidays/countries/marshall_islands.py
holidays/countries/united_states.py
tests/countries/test_marshall_islands.py
tests/countries/test_united_states.py

Add Northern Mariana Islands (ISO-3666-2 code US-MP)

Add Northern Mariana Islands (ISO-3666-2 code US-MP)

---

README.rst
holidays/countries/poland.py
holidays/locale/en/LC_MESSAGES/PL.po
holidays/locale/uk/LC_MESSAGES/PL.po
tests/countries/test_poland.py

- added historical holidays
- added Ukrainian translation
- refactored tests

Update Poland holidays, add uk localization

---

holidays/countries/azerbaijan.py
tests/countries/test_azerbaijan.py

Maybe it's not the best implementation, but I tried. :) @arkid15r, look, please.

Optimize Azerbaijan observed holidays

---

README.rst
holidays/countries/colombia.py
holidays/locale/en_US/LC_MESSAGES/CO.po
holidays/locale/es/LC_MESSAGES/CO.po
holidays/locale/uk/LC_MESSAGES/CO.po
tests/countries/test_colombia.py

Add Colombia holidays localization: en_US, es, uk

---

README.rst
holidays/countries/monaco.py
holidays/locale/en_US/LC_MESSAGES/MC.po
holidays/locale/fr/LC_MESSAGES/MC.po
holidays/locale/uk/LC_MESSAGES/MC.po
tests/countries/test_monaco.py

Add Monaco holidays localization: en_US, fr, uk

---

README.rst
holidays/countries/peru.py
holidays/locale/en_US/LC_MESSAGES/PE.po
holidays/locale/es/LC_MESSAGES/PE.po
holidays/locale/uk/LC_MESSAGES/PE.po
tests/countries/test_peru.py

Add Peru holidays localization: en_US, es, uk

---

holidays/countries/nigeria.py
tests/countries/test_nigeria.py

Reverts dr-prodigy/python-holidays#978

Revert "Optimize Nigeria observed holidays"

---

holidays/countries/argentina.py
holidays/locale/en_US/LC_MESSAGES/AR.po
holidays/locale/es/LC_MESSAGES/AR.po
holidays/locale/uk/LC_MESSAGES/AR.po
tests/countries/test_argentina.py

This fixes movable holidays logic for #465 as per [***LEY DE ESTABLECIMIENTO DE FERIADOS Y FINES DE SEMANAS LARGOS N° 27399***](https://www.argentina.gob.ar/normativa/nacional/ley-27399-281835/texto), as well as implementing bridge holidays and special cases per related Argentinian Law I could find online with Google Translates and their updated test cases.
This pretty much sums the changed logic here:
```java
!!! Movable Holidays Law !!!
- Decreto 52/2017: 2017-01-23 (Reconfirmed in Ley 27399)
- If TUE/WED ← observed on previous MON
- If THUR/FRI/SAT/SUN ← observed on next MON
^^^
Changed to THUR/FRI only, this does not applies to SAT/SUN as per the official calendar
and the actual law (Argentinian Wikipedia is wrong)
```
I think I might need to request @leandrorojas 's assistance here …

Improve Argentina holidays

---

README.rst
holidays/countries/chile.py
holidays/locale/en_US/LC_MESSAGES/CL.po
holidays/locale/es/LC_MESSAGES/CL.po
holidays/locale/uk/LC_MESSAGES/CL.po
tests/countries/test_chile.py

- Add Chile holidays localization: en_US, es (default), uk
- Some holidays original names correction

Update Chile holidays. Add localization: en_US, es, uk

---

tox.ini

Fixed tox.ini typo

---

.pre-commit-config.yaml

Bump mypy to v1.1.1

---

holidays/countries/denmark.py
tests/countries/test_denmark.py

See https://www.ft.dk/samling/20222/lovforslag/l13/index.htm.
- [x ] I've followed the [contributing guidelines][contributing-guidelines]
- [x ] This PR is filed against `beta` branch of the repository
- [x ] This PR doesn't contain any merge conflicts and has clean commit history
- [x ] The code style looks good (`make pre-commit`)
- [x ] I've added tests to verify that the new code works and all tests pass locally (`make test`, `make tox`)
- [x ] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

Update Denmark holidays: remove "Store bededag" starting 2024

---

holidays/countries/ukraine.py
holidays/locale/en_US/LC_MESSAGES/UA.po
holidays/locale/uk/LC_MESSAGES/UA.po
tests/countries/test_ukraine.py

There is no holidays in Ukraine during the period of martial law: [Law No. 2136-IX](https://zakon.rada.gov.ua/laws/show/2136-20#n26).
Also removed Soviet-era holidays (before 1991).

Update Ukraine holidays

---

holidays/locale/fr/LC_MESSAGES/CA.po

Fix Memorial Day translation typo.

Update Canada localization: fr

---

holidays/financial/ny_stock_exchange.py
tests/financial/test_ny_stock_exchange.py

Refactor NYSE holidays and tests.

Refactor NYSE holidays

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template.

---

.github/workflows/ci-cd.yml
MANIFEST.in
Makefile
requirements/dev.txt
scripts/l10n/generate_mo_files.py
setup.py

Update package build process. Fix source distribution file list.
Resolves #1008.

Update package build process

---

.github/workflows/ci-cd.yml
MANIFEST.in
Makefile

Rename distribution build target in order to resolve local directory name conflict.

Fix distribution build

---

.pre-commit-config.yaml

Update pre-commit: bump rstcheck version to v6.1.2

Bump pre-commit rstcheck version to 6.1.2

---

holidays/locale/uk/LC_MESSAGES/UY.po

Update Uruguay localization: fix uk translation

---

README.rst
holidays/countries/andorra.py
tests/countries/test_andorra.py

Update holidays of Canillo, Sant Julià de Lòria, Andorra la Vella.

Update Andorra parish holidays

---

holidays/countries/albania.py
holidays/countries/american_samoa.py
holidays/countries/andorra.py
holidays/countries/guam.py
holidays/countries/montenegro.py
holidays/countries/northern_mariana_islands.py
holidays/countries/panama.py
holidays/countries/puerto_rico.py
holidays/countries/san_marino.py
holidays/countries/united_states_minor_outlying_islands.py
holidays/countries/united_states_virgin_islands.py
holidays/countries/vatican_city.py
tests/countries/test_albania.py
tests/countries/test_andorra.py
tests/countries/test_montenegro.py
tests/countries/test_san_marino.py
tests/countries/test_vatican_city.py
tests/test_calendars.py
tests/test_utils.py

File headers updates (copyright 2023, reference email).

Unify file headers

---

.github/PULL_REQUEST_TEMPLATE.md

Mention documentation in the PR template

Update PR template: add documentation mentioning

---

holidays/utils.py

Add `@lru_cache` for `utils::list_supported_countries()` and `utils::list_supported_financial()`.

Memoize list supported entities methods results

---

README.rst
holidays/countries/romania.py
holidays/locale/en_US/LC_MESSAGES/RO.po
holidays/locale/ro/LC_MESSAGES/RO.po
holidays/locale/uk/LC_MESSAGES/RO.po
tests/countries/test_romania.py

Update Romania holidays, localization (en_US, ro, uk).

Update Romania holidays, localization

---

holidays/countries/dominican_republic.py
tests/countries/test_dominican_republic.py

Refactor Dominican Republic movable holidays.

Refactor Dominican Republic movable holidays

---

.github/PULL_REQUEST_TEMPLATE.md

Update tests checkbox wording.

Update PR template: rework tests related action item wording

---

README.rst
holidays/countries/__init__.py
holidays/countries/costa_rica.py
holidays/locale/en_US/LC_MESSAGES/CR.po
holidays/locale/es/LC_MESSAGES/CR.po
holidays/locale/uk/LC_MESSAGES/CR.po
tests/countries/test_costa_rica.py

Add Costa Rica holidays, with en_US, es (default), uk localization.

Add Costa Rica holidays

---

holidays/countries/portugal.py
holidays/locale/en_US/LC_MESSAGES/PT.po
holidays/locale/pt_PT/LC_MESSAGES/PT.po

This migrates Portugal's holidays to the newer `holiday_groups` standard.
Perhaps these Christian holidays in Portugal could be converted to Holiday groups too?
- **St. Anthony Day** (JUN, 13)
- **Feast of Our Lady of Sorrows** (AUG, 20)
- **St. Matthew's Day** (SEP, 21)

Migrate Portugal holidays to holiday groups

---

holidays/countries/south_korea.py
tests/countries/test_south_korea.py

Refactor South Korea: alternative holidays optimization.

Refactor South Korea holidays: optimize alternative holidays

---

README.rst
holidays/countries/france.py
holidays/locale/en_US/LC_MESSAGES/FR.po
holidays/locale/fr/LC_MESSAGES/FR.po
holidays/locale/uk/LC_MESSAGES/FR.po
tests/countries/test_france.py

- migrate to holidays groups
- fix some holidays date / starting date
- en_US, fr (default), uk localization

Update France holidays, localization

---

holidays/countries/ukraine.py

Migrate Ukraine holidays to `holiday_groups` standard.

Migrate Ukraine holidays to holiday groups

---

holidays/countries/portugal.py
holidays/holiday_base.py

Streamline subdivision code handling and improve readability.
Portugal: use holiday groups, split subdivision holidays.

Introduce subdivision holidays methods

---

holidays/holiday_base.py
tests/test_holiday_base.py

Add istartswith/startswith lookups to `get_named()`

Extend `get_named()` lookup types: add `[i]startswith`

---

holidays/countries/canada.py
tests/countries/test_canada.py

Fix Canada localization (observed holidays didn't translate correctly).

Fix Canada localization

---

.github/workflows/ci-cd.yml

Add polib as a deploy process dependency

---

.pre-commit-config.yaml
tox.ini

Update tox.ini formatting.
Bump pre-commit black version from 23.1.0 to 23.3.0, tox-ini-fmt from 0.6.1 to 1.0.0

Bump pre-commit black and tox-ini-fmt versions

---

holidays/countries/jamaica.py
tests/countries/test_jamaica.py

Migrate Jamaica holidays to `holiday_groups` standard.

Migrate Jamaica holidays to holiday groups

---

holidays/countries/australia.py
tests/countries/test_australia.py

Migrate Australia holidays to holiday groups and subdivision holidays methods.

Migrate Australia holidays to holiday groups and subdivision holidays methods

---

README.rst
holidays/countries/__init__.py
holidays/countries/ecuador.py
holidays/locale/en_US/LC_MESSAGES/EC.po
holidays/locale/es/LC_MESSAGES/EC.po
holidays/locale/uk/LC_MESSAGES/EC.po
tests/countries/test_ecuador.py

Add Ecuador holidays (en_US, es, uk localization).

Add Ecuador holidays

---

holidays/countries/spain.py
tests/countries/test_spain.py

Migrate Spain holidays to holiday groups and subdivision holidays methods.

Migrate Spain holidays to holiday groups and subdivision holidays methods

---

tests/countries/test_germany.py
tests/countries/test_malaysia.py
tests/countries/test_portugal.py
tests/countries/test_switzerland.py
tests/countries/test_thailand.py

Refactoring Switzerland, Germany, Malaysia, Thailand, Portugal tests.

Refactor long running countries tests

---

holidays/countries/japan.py
holidays/locale/en_US/LC_MESSAGES/JP.po
holidays/locale/ja/LC_MESSAGES/JP.po

Refactor Japan observed holidays (performance optimization).

Refactor Japan observed holidays

---

holidays/calendars.py
tests/test_utils.py

Cast `Gregorian` to `date` for hijri_conver holidays.
Add tests checking holiday's date type.

Normalize holidays dict keys type

---

.github/workflows/ci-cd.yml

Make sure build process runs successfully.

Add distribution build tests

---

.github/dependabot.yml

Set `beta` as a target branch. Move the jobs run from FRI to WED.

Reconfigure dependabot

---

holidays/countries/chile.py
holidays/countries/japan.py
requirements/dev.txt
setup.cfg
tests/countries/test_japan.py

Refactor astronomic holidays (Chile and Japan) without using external functions (instead, simple interpolation functions are used, 100% accurate till the end of XXI century). This allows to remove `PyMeeus`, `backports.zoneinfo` and `tzdata` from dependencies.

Refactor astronomic holidays

---

README.rst
holidays/countries/denmark.py
holidays/countries/finland.py
holidays/countries/iceland.py
holidays/countries/norway.py
holidays/countries/sweden.py
holidays/locale/da/LC_MESSAGES/DK.po
holidays/locale/en_US/LC_MESSAGES/DK.po
holidays/locale/en_US/LC_MESSAGES/FI.po
holidays/locale/en_US/LC_MESSAGES/IS.po
holidays/locale/en_US/LC_MESSAGES/NO.po
holidays/locale/en_US/LC_MESSAGES/SE.po
holidays/locale/fi/LC_MESSAGES/FI.po
holidays/locale/is/LC_MESSAGES/IS.po
holidays/locale/no/LC_MESSAGES/NO.po
holidays/locale/sv/LC_MESSAGES/FI.po
holidays/locale/sv/LC_MESSAGES/SE.po
holidays/locale/uk/LC_MESSAGES/DK.po
holidays/locale/uk/LC_MESSAGES/FI.po
holidays/locale/uk/LC_MESSAGES/IS.po
holidays/locale/uk/LC_MESSAGES/NO.po
holidays/locale/uk/LC_MESSAGES/SE.po
tests/countries/test_denmark.py
tests/countries/test_finland.py
tests/countries/test_iceland.py
tests/countries/test_norway.py
tests/countries/test_sweden.py

Migrate Scandinavian countries holidays to `holiday_groups` standard and localization:
- Denmark: da (default), en_US, uk
- Finland: en_US, fi (default), sv, uk
- Iceland: en_US, is (default), uk
- Norway: en_US, no (default), uk
- Sweden: en_US, sv (default), uk

Migrate Scandinavian countries holidays to holiday groups

---

holidays/countries/argentina.py
holidays/countries/armenia.py
holidays/countries/bahrain.py
holidays/countries/belarus.py
holidays/countries/chile.py
holidays/countries/costa_rica.py
holidays/countries/cyprus.py
holidays/countries/djibouti.py
holidays/countries/ecuador.py
holidays/countries/egypt.py
holidays/countries/ethiopia.py
holidays/countries/france.py
holidays/countries/india.py
holidays/countries/lithuania.py
holidays/countries/moldova.py
holidays/countries/monaco.py
holidays/countries/peru.py
holidays/countries/portugal.py
holidays/countries/romania.py
holidays/countries/serbia.py
holidays/countries/south_korea.py
holidays/countries/spain.py
holidays/countries/turkey.py
holidays/countries/ukraine.py
holidays/countries/uruguay.py
holidays/countries/venezuela.py
holidays/countries/vietnam.py
holidays/holiday_groups.py

Rename _add_labour_day to _add_labor_day.
Rearrange methods.

Update InternationalHolidays:_add_labour_day method

---

README.rst
holidays/countries/netherlands.py
holidays/locale/en_US/LC_MESSAGES/NL.po
holidays/locale/nl/LC_MESSAGES/NL.po
holidays/locale/uk/LC_MESSAGES/NL.po
tests/countries/test_netherlands.py

Migrate Netherlands holidays to `holiday_groups` standard, localization (en_US, nl, uk).

Migrate Netherlands holidays to holiday groups, localization

---

.github/workflows/ci-cd.yml

Use artifacts to restore the deploy process.

Fix deploy process

---

.github/workflows/ci-cd.yml

Fix Github deploy job: update artifacts name.

Update artifact name

---

.github/workflows/ci-cd.yml

Another attempt to share build artifacts.

Fix deploy: add missing path parameter

---

holidays/countries/albania.py
holidays/countries/bosnia_and_herzegovina.py
holidays/countries/burundi.py
holidays/countries/kazakhstan.py
holidays/countries/kyrgyzstan.py
holidays/countries/morocco.py
holidays/countries/nigeria.py
holidays/countries/north_macedonia.py
holidays/countries/pakistan.py
holidays/countries/philippines.py
holidays/countries/tunisia.py
holidays/countries/united_arab_emirates.py
holidays/countries/uzbekistan.py
tests/countries/test_albania.py
tests/countries/test_bosnia_and_herzegovina.py
tests/countries/test_burundi.py
tests/countries/test_morocco.py
tests/countries/test_nigeria.py
tests/countries/test_north_macedonia.py
tests/countries/test_pakistan.py
tests/countries/test_philippines.py
tests/countries/test_tunisia.py
tests/countries/test_united_arab_emirates.py
tests/countries/test_uzbekistan.py

Migrate countries with Islamic holidays to `holiday_groups` standard:
- Albania
- Bosnia and Herzegovina
- Burundi
- Kazakhstan
- Kyrgyzstan
- Morocco
- Nigeria
- North Macedonia
- Pakistan
- Philippines
- Tunisia
- United Arab Emirates
- Uzbekistan

Migrate Islamic holidays countries to holiday groups

---

holidays/countries/vietnam.py
tests/countries/test_vietnam.py

Actually [Vietnamese calendar](https://en.wikipedia.org/wiki/Vietnamese_calendar) is mostly based on the lunisolar Chinese calendar, not Korean (which, in fact, is also a slightly modified Chinese).

Switch Vietnam holidays from Korean to Chinese lunisolar calendar

---

holidays/countries/angola.py
holidays/countries/botswana.py
holidays/countries/chile.py
holidays/countries/united_states.py
holidays/holiday_base.py

Refactor weekday helpers: extend args to accept month/day tuple

Refactor weekday helpers: extend args to accept month/day tuple

---

.github/workflows/ci-cd.yml
Makefile
requirements/dev.txt
requirements/runtime.txt
requirements/tests.txt
tox.ini

Optimize CI/CD stages (remove redundant dependencies installation).

Optimize CI/CD stages

---

holidays/countries/indonesia.py
tests/countries/test_indonesia.py

Migrate Indonesia holidays to `holiday_groups` standard.
"Hari Raya Waisak" calculation as 15th day of 4th month by Chinese calendar is exactly equal to `_ChineseLuniSolar::vesak_date()`.

Migrate Indonesia holidays to holiday groups

---

holidays/countries/singapore.py

Migrate Singapore holidays to `holiday_groups` standard.
"Vesak Day" calculated as 15th day of 4th month by Chinese calendar, "Deepavali" - as (1st day of 10th month) - 2 days. It's exactly equal to `_ChineseLuniSolar::vesak_date()` and `_ChineseLuniSolar::s_diwali_date()`.

Migrate Singapore holidays to holiday groups

---

holidays/countries/thailand.py
holidays/locale/en_US/LC_MESSAGES/TH.po
holidays/locale/th/LC_MESSAGES/TH.po
tests/countries/test_thailand.py

Migrates Thailand holidays to `holiday_group` standard.
This PR also implements #1106's new localization test methods and expands the loc's test case to cover all of the 2022 holidays.

Migrate Thailand holidays to holiday groups

---

holidays/countries/malaysia.py
tests/countries/test_malaysia.py

Migrate Malaysia holidays to `holiday_groups` standard.

Migrate Malaysia holidays to holiday groups

---

holidays/countries/malaysia.py
holidays/countries/singapore.py

Unify code structure for Malaysia and Singapore

Unify code structure for Malaysia and Singapore

---

holidays/countries/albania.py
holidays/countries/bosnia_and_herzegovina.py
holidays/holiday_groups.py

Change `holiday_name` to `name`.
Update ChristianHolidays group:
- Add `calendar` option for Easter holidays
- Rearrange methods (ABC)
- Remove `_set_calendar` method
- Update AL, BA

Update holiday groups: extend Easter methods

---

holidays/countries/brazil.py
tests/countries/test_brazil.py

Migrate Brazil holidays to `holiday_groups` and subdivision holidays methods.

Migrate Brazil holidays to holiday groups and subdivision holidays methods

---

holidays/countries/russia.py
holidays/locale/en_US/LC_MESSAGES/RU.po
tests/countries/test_russia.py

Added missing bridge days for Russia for 2023. Determined yearly by the government: https://www.consultant.ru/document/cons_doc_LAW_425407/

Added missing bridge days for Russia for 2023

---

tests/countries/test_chile.py

Update Chile tests (for complete coverage).

Update Chile tests

---

README.rst
holidays/countries/slovakia.py
holidays/locale/en_US/LC_MESSAGES/SK.po
holidays/locale/sk/LC_MESSAGES/SK.po
holidays/locale/uk/LC_MESSAGES/SK.po
tests/countries/test_slovakia.py

Update Slovakia holidays, localization (en_US, sk, uk).

Update Slovakia holidays, localization

---

.pre-commit-config.yaml

Bump mypy version from 1.2.0 to 1.3.0

Bump mypy version from 1.2.0 to 1.3.0

---

holidays/holiday_base.py

Reorder HolidayBase methods -- no real changes --  just moved the code around.

Reorder HolidayBase methods

---

holidays/financial/european_central_bank.py
holidays/financial/ny_stock_exchange.py

Migrate financial to holiday groups.

Migrate financial to holiday groups

---

README.rst
holidays/countries/__init__.py
holidays/countries/belize.py
holidays/registry.py
tests/countries/test_belize.py

Add Belize holidays (close #1154).

Add Belize holidays

---

tests/countries/test_argentina.py
tests/countries/test_armenia.py
tests/countries/test_bolivia.py
tests/countries/test_botswana.py
tests/countries/test_eswatini.py
tests/countries/test_kazakhstan.py
tests/countries/test_kenya.py
tests/countries/test_uruguay.py
tests/countries/test_venezuela.py

Refactoring long running tests (Argentina, Armenia, Bolivia, Botswana, Eswatini, Kazakhstan, Kenya, Uruguay, Venezuela).

Refactor long running tests

---

tests/countries/test_singapore.py

Update Singapore tests, restore entity 100% coverage.

Update Singapore tests: cover non-observed holidays

---

holidays/countries/morocco.py
tests/countries/test_morocco.py

Update Morocco holidays, add Amazigh new year since Morocco recongnized it as an official holiday this month

Update Morocco holidays

---

holidays/countries/vatican_city.py
tests/countries/test_vatican_city.py

Update Vatican City holidays

---

holidays/registry.py
tests/test_registry.py

Add an error message for backward incompatible inheritance use cases.

Add EntityLoader inheritance error message

---

holidays/calendars/__init__.py
holidays/calendars/hebrew.py
holidays/calendars/thai.py
holidays/countries/israel.py
holidays/countries/thailand.py
tests/test_calendars.py

Update Lunisolar calendar naming based on @mborsetti's suggestion.

Update calendar naming: fix grammar

---

holidays/countries/azerbaijan.py

Refactor Azerbaijan islamic holidays (`_CustomCalendar` support).

Update Azerbaijan holidays: use custom Islamic calendar

---

scripts/calendar/asian_generator.py

Add script for Asian calendars classes (Buddhist, Chinese, Hindu) code generation (#1124).

Add Asian calendars classes code generator

---

holidays/holiday_groups.py
tests/test_holiday_base.py

Update test coverage: fix uncovered lines

---

README.rst
holidays/countries/__init__.py
holidays/countries/cameroon.py
holidays/registry.py
tests/countries/test_cameroon.py

Add Cameroon holidays (close #1161).

Add Cameroon holidays

---

holidays/countries/kenya.py

Migrate Kenya holidays to `holiday_groups` standard.

Migrate Kenya holidays to holiday groups

---

holidays/countries/montenegro.py

Migrate Montenegro holidays to holiday groups

Migrate Montenegro holidays to holiday groups

---

README.rst
holidays/countries/__init__.py
holidays/countries/gabon.py
holidays/registry.py
tests/countries/test_gabon.py

Add Gabon holidays (close #1189).

Add Gabon holidays

---

holidays/calendars/__init__.py
holidays/calendars/buddhist.py
holidays/calendars/chinese.py
holidays/calendars/hindu.py
holidays/calendars/islamic.py
holidays/countries/azerbaijan.py
holidays/countries/bahrain.py
holidays/countries/indonesia.py
holidays/countries/malaysia.py
holidays/countries/pakistan.py
holidays/countries/singapore.py
holidays/countries/united_arab_emirates.py
holidays/holiday_groups.py

The optimizations:
- Create custom calandar base class for Buddhist, Chinese, Hindu, and Islamic calendars
- Move `show_estimated` into calendars

Refactor calendars: optimize inheritance and scope

---

holidays/countries/greece.py
holidays/locale/el/LC_MESSAGES/GR.po
holidays/locale/en_US/LC_MESSAGES/GR.po
tests/countries/test_greece.py

Add Good Friday (close #1255), refactor tests.

Update Greece holidays: add Good Friday

---

holidays/countries/angola.py

Migrate Angola holidays to holiday groups

Migrate Angola holidays to holiday groups

---

.pre-commit-config.yaml
setup.cfg

This PR migrates `setup cfg fmt` to v2.3.0 as per done automatically with `tox` command.

Bump setup-cfg-fmt version from 2.2.0 to 2.3.0

---

holidays/countries/cameroon.py
holidays/countries/gabon.py
holidays/countries/south_korea.py

Migrate remaining countries (South Korea, Cameroon, Gabon) to custom calendar types.

Migrate remaining countries to custom calendar types

---

tests/countries/test_isle_of_man.py

Add Isle Of Man 1970 test

---

holidays/holiday_base.py
tests/test_holiday_base.py

Closes #1281 
Extend `HolidayBase::pop_named`:
- Allow to pop the entire date by exact (combined) multiple holiday name
- Allow to pop a single holiday by its name for a multiple holiday date

Refactor HolidayBase::pop_named

---

tests/common.py
tests/test_registry.py
tests/test_utils.py

Run entity import tests on latest Python version only.

Run entity import tests on latest Python version only

---

README.rst
tests/common.py

Allow using ISO 639-2 (three-letter) language codes

Allow using ISO 639-2 (three-letter) language codes

---

.pre-commit-config.yaml

Bump tox-ini-fmt from 1.3.0 to 1.3.1

---

.pre-commit-config.yaml
pyproject.toml

Clean up configuration files

---

.pre-commit-config.yaml

Bump mypy from 1.3.0 to 1.4.0

---

.github/workflows/ci-cd.yml
pyproject.toml
setup.cfg
tox.ini

Drop Python 3.7 support

---

.pre-commit-config.yaml
Makefile
holidays/__init__.py
holidays/calendars/__init__.py
holidays/countries/__init__.py
holidays/financial/__init__.py
holidays/groups/__init__.py
pyproject.toml
scripts/generate_release_notes.py
setup.cfg

Clean up the configs:
- Remove unused configs
- Update Makefile l10n target to be less verbose
- Reduce flake8 per-file-ignores item number

Update configuration files

---

holidays/countries/united_states.py
tests/countries/test_united_states.py
tests/test_holiday_base.py

Migrate United States holidays to `holiday_groups` standard and subdivision holidays methods.

Migrate United States holidays to holiday groups and subdivision holidays methods

---

holidays/countries/ireland.py
tests/countries/test_ireland.py

Migrate Ireland holidays to `holiday_groups` standard.

Migrate Ireland holidays to holiday groups

---

README.rst
holidays/countries/madagascar.py
holidays/locale/en_US/LC_MESSAGES/MG.po
holidays/locale/mg/LC_MESSAGES/MG.po
holidays/locale/uk/LC_MESSAGES/MG.po
tests/countries/test_madagascar.py

Migrate Madagascar to `holiday_groups`, add l10n support.

Migrate Madagascar to holiday groups, add l10n support

---

README.rst
holidays/countries/bosnia_and_herzegovina.py
holidays/locale/bs/LC_MESSAGES/BA.po
holidays/locale/en_US/LC_MESSAGES/BA.po
holidays/locale/sr/LC_MESSAGES/BA.po
holidays/locale/uk/LC_MESSAGES/BA.po
tests/countries/test_bosnia_and_herzegovina.py

- update holiday names to official
- change subdivision names to [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:BA)
- observed holidays for all subdivisions
- localization (bs, en_US, sr, uk)

Update Bosnia and Herzegovina holidays, add l10n support

---

README.rst
holidays/countries/malta.py
holidays/locale/en_MT/LC_MESSAGES/MT.po
holidays/locale/en_US/LC_MESSAGES/MT.po
holidays/locale/mt/LC_MESSAGES/MT.po
tests/countries/test_malta.py

Migrate Malta to `holiday_groups`, add l10n support.
Also introduce appropriate historical holiday introduction date as seen in `NATIONAL HOLIDAYS AND OTHER PUBLIC HOLIDAYS ACT` [from its 1980 amendment onwards (the earliest version online in-full)](https://legislation.mt/eli/cap/252/20210212/eng).

Migrate Malta to `holiday_groups`, add l10n support

---

.pre-commit-config.yaml

Bump `mypy` from 1.4.0 to 1.4.1.

Bump mypy from 1.4.0 to 1.4.1

---

README.rst
holidays/countries/estonia.py
holidays/countries/latvia.py
holidays/countries/lithuania.py
holidays/locale/en_US/LC_MESSAGES/EE.po
holidays/locale/en_US/LC_MESSAGES/LT.po
holidays/locale/en_US/LC_MESSAGES/LV.po
holidays/locale/et/LC_MESSAGES/EE.po
holidays/locale/lt/LC_MESSAGES/LT.po
holidays/locale/lv/LC_MESSAGES/LV.po
holidays/locale/uk/LC_MESSAGES/EE.po
holidays/locale/uk/LC_MESSAGES/LT.po
holidays/locale/uk/LC_MESSAGES/LV.po
tests/countries/test_estonia.py
tests/countries/test_latvia.py
tests/countries/test_lithuania.py

Estonia, Latvia, Lithuania:
- update holiday names and relevance periods
- migrate Estonia and Latvia to `holiday_groups`
- add l10n support (official language + en_US, uk)

Update Baltic countries holidays, add l10n support

---

holidays/countries/marshall_islands.py
tests/countries/test_marshall_islands.py

This PR migrates Marshal Islands to `holiday_groups`, as well as fixing incorrect in-lieu observances and extending support to 2020 with data from Internet Archives.

Migrate Marshall Islands to `holiday_groups`

---

holidays/constants.py
holidays/countries/slovakia.py
holidays/holiday_base.py
tests/countries/test_austria.py
tests/countries/test_slovakia.py

- Add special holidays categories support (special_public_holidays, special_bank_holidays etc)
- Add "workday" category, for official state holidays that are not non-working days (October 28 in Slovakia as an example)

Add special holidays categories support

---

tests/countries/test_marshall_islands.py

Fix Marshall Islands tests warning.

Fix Marshall Islands tests warning

---

README.rst
holidays/countries/belgium.py
holidays/countries/luxembourg.py
holidays/locale/de/LC_MESSAGES/BE.po
holidays/locale/de/LC_MESSAGES/LU.po
holidays/locale/en_US/LC_MESSAGES/BE.po
holidays/locale/en_US/LC_MESSAGES/LU.po
holidays/locale/fr/LC_MESSAGES/BE.po
holidays/locale/fr/LC_MESSAGES/LU.po
holidays/locale/lb/LC_MESSAGES/LU.po
holidays/locale/nl/LC_MESSAGES/BE.po
holidays/locale/uk/LC_MESSAGES/BE.po
holidays/locale/uk/LC_MESSAGES/LU.po
tests/countries/test_belgium.py
tests/countries/test_luxembourg.py

Belgium and Luxembourg:
- migrate to `holiday_groups`
- add l10n support (Belgium - de, en_US, fr, **nl**, uk, Luxembourg - de, en_US, fr, **lb**, uk)

Migrate Belgium and Luxembourg to holiday groups, add l10n support

---

README.rst
holidays/countries/croatia.py
holidays/countries/czechia.py
holidays/countries/slovenia.py
holidays/locale/cs/LC_MESSAGES/CZ.po
holidays/locale/en_US/LC_MESSAGES/CZ.po
holidays/locale/en_US/LC_MESSAGES/HR.po
holidays/locale/en_US/LC_MESSAGES/SI.po
holidays/locale/hr/LC_MESSAGES/HR.po
holidays/locale/sl/LC_MESSAGES/SI.po
holidays/locale/uk/LC_MESSAGES/CZ.po
holidays/locale/uk/LC_MESSAGES/HR.po
holidays/locale/uk/LC_MESSAGES/SI.po
tests/countries/test_croatia.py
tests/countries/test_czechia.py
tests/countries/test_slovenia.py

- migrate to `holiday_groups`
- add l10n support (Croatia - en_US, **hr**, uk, Czechia - **cs**, en_US, uk, Slovenia - en_US, **sl**, uk)

Migrate Croatia, Czechia and Slovenia to holiday groups, add l10n support

---

holidays/countries/ireland.py

Ireland holidays changes that have not been merged from #1333.

Update Ireland holidays: finish migration to holiday groups

---

holidays/countries/united_kingdom.py
tests/countries/test_united_kingdom.py

Update United Kingdom holidays:
- New Year's Day in ENG, NIR, WLS officially introduced since 1975
- St. Patrick's Day (NIR) - since 1903
- St. Andrew's Day (SCT) - since 2006
- Boxing Day in SCT - since 1974

Update United Kingdom holidays: update certain holidays start years

---

holidays/countries/argentina.py
holidays/countries/belize.py
holidays/countries/chile.py
holidays/countries/colombia.py
holidays/countries/costa_rica.py
holidays/countries/dominican_republic.py
holidays/countries/ecuador.py

Refactor movable holidays (LATAM countries).

Refactor movable holidays

---

.pre-commit-config.yaml

Bump setup-cfg-fmt version from 2.3.0 to 2.4.0

Bump setup-cfg-fmt version from 2.3.0 to 2.4.0

---

holidays/countries/bosnia_and_herzegovina.py
holidays/countries/botswana.py
holidays/countries/china.py
holidays/countries/hungary.py
holidays/countries/montenegro.py
holidays/countries/serbia.py
holidays/countries/slovenia.py
holidays/countries/ukraine.py
holidays/groups/international.py

Add May 2 and 3 (as `_add_labor_day_two()` and `_add_labor_day_three()`) to `InternationalHolidays` class.

Update InternationalHolidays group: add May 2 and 3

---

holidays/holiday_base.py

Refactor `HolidayBase::get_named()` method.
```python
from timeit import timeit
t_setup = "from holidays.countries.united_states import US; country = US(years=2022)"
t_code = "r = country.get_named('Independence Day')"
t_number = 100_000
lookups = ("icontains", "exact", "contains", "startswith", "iexact", "istartswith")
times = {
lookup: timeit(t_code, setup=t_setup, number=t_number) for lookup in lookups
}
for lookup in lookups:
print(f"{lookup:11}  {times[lookup]:.3f}")
```
|    Test   |  beta  |   PR   |
|:---------:|:------:|:------:|
|icontains  |  1.008 |  0.505 |
|exact      |  0.931 |  0.507 |
|contains   |  0.919 |  0.563 |
|startswith |  0.973 |  0.564 |
|iexact     |  0.931 |  0.518 |
|istartswith|  0.938 |  0.513 |
[contributing-guidelines]: …

Refactor HolidayBase::get_named() method

---

.pre-commit-config.yaml

Bump black version from 23.3.0 to 23.7.0

Bump black version from 23.3.0 to 23.7.0

---

scripts/l10n/generate_po_files.py

Optimize .po files overwriting (don't overwrite file if it hasn't changed).

Optimize .po files overwriting

---

holidays/holiday_base.py
scripts/calendar/asian_generator.py
scripts/calendar/hebrew_generator.py
scripts/calendar/islamic_generator.py
scripts/generate_release_notes.py
tests/test_docs.py

Replace `open` and `os.path` with `pathlib.Path`.

Use pathlib.Path for path operations

---

holidays/countries/bangladesh.py
holidays/countries/russia.py
holidays/locale/en_US/LC_MESSAGES/RU.po
holidays/locale/ru/LC_MESSAGES/RU.po
tests/countries/test_bangladesh.py
tests/countries/test_russia.py

Complete migration to holiday groups (migrate Bangladesh and Russia).

Migrate Bangladesh and Russia to holiday groups

---

holidays/countries/taiwan.py
tests/countries/test_taiwan.py

Update Taiwan holidays

---

README.rst
holidays/countries/djibouti.py
holidays/locale/ar/LC_MESSAGES/DJ.po
holidays/locale/en_US/LC_MESSAGES/DJ.po
holidays/locale/fr/LC_MESSAGES/DJ.po
tests/countries/test_djibouti.py

Update Djibouti holidays, add l10n support (ar, en_US, **fr**).

Update Djibouti holidays, add l10n support

---

README.rst
holidays/countries/morocco.py
holidays/locale/ar/LC_MESSAGES/MA.po
holidays/locale/fr/LC_MESSAGES/MA.po
tests/countries/test_morocco.py

Morocco holidays fr localization.

Update Morocco holidays: add fr localization

---

README.rst
holidays/countries/angola.py
holidays/locale/en_US/LC_MESSAGES/AO.po
holidays/locale/pt_AO/LC_MESSAGES/AO.po
holidays/locale/uk/LC_MESSAGES/AO.po
tests/countries/test_angola.py

Update Angola holidays, add l10n support (en_US, **pt_AO**, uk).

Update Angola holidays, add l10n support

---

.github/workflows/ci-cd.yml
tox.ini

Add Python 3.12.0-beta.4 to the test environment list

Add Python 3.12.0-beta.4 environment

---

holidays/calendars/__init__.py
holidays/calendars/julian_revised.py
holidays/calendars/revised_julian.py
holidays/countries/bulgaria.py
holidays/countries/cyprus.py
holidays/countries/greece.py
holidays/countries/romania.py
holidays/groups/christian.py

Add JULIAN_REVISED_CALENDAR calendar constant (close #1378).

Add JULIAN_REVISED_CALENDAR calendar

---

holidays/holiday_base.py
tests/test_holiday_base.py

Add substituted holidays test (restore 100% test coverage).

Add substituted holidays test

---

README.rst
holidays/countries/mozambique.py
holidays/locale/en_US/LC_MESSAGES/MZ.po
holidays/locale/pt_MZ/LC_MESSAGES/MZ.po
holidays/locale/uk/LC_MESSAGES/MZ.po
tests/countries/test_mozambique.py

Update Mozambique holidays, add l10n support (en_US, **pt_MZ**, uk).

Update Mozambique holidays, add l10n support

---

README.rst
holidays/countries/bolivia.py
holidays/locale/en_US/LC_MESSAGES/BO.po
holidays/locale/es/LC_MESSAGES/BO.po
holidays/locale/uk/LC_MESSAGES/BO.po
tests/countries/test_bolivia.py

Update Bolivia holidays, add l10n support (en_US, **es**, uk).

Update Bolivia holidays, add l10n support

---

holidays/countries/south_korea.py
tests/countries/test_south_korea.py

Update South Korea holidays:
- refactor alternative holiday population
- change some holidays name
- add special holidays
- move Labour Day to bank holidays

Update South Korea holidays

---

holidays/countries/thailand.py
tests/countries/test_thailand.py

[The Thai government announced an additional in-lieu holiday on Monday, July 31, 2023](https://www.komchadluek.net/news/politics/554407) today to create a 6-days long holiday period with the aim of encouraging domestic tourism:
| Weekday | Date | Significance |
| --- | --- | --- |
| Friday | July 28 | **HM King Maha Vajiralongkorn's Birthday** |
| Saturday | July 29 | Weekends |
| Sunday | July 30 | Weekends |
| **`Monday`** | **`July 31`** | **`Special In Lieu Holiday (New)`** |
| Tuesday | August 1 | **Asarnha Bucha** |
| Wednesday | August 2 | **Buddhist Lent Day** |

Add Special In Lieu Holiday on July 31, 2023 for Thailand

---

holidays/countries/bahrain.py
holidays/countries/bangladesh.py
holidays/countries/belarus.py
holidays/countries/belgium.py
holidays/countries/belize.py
holidays/countries/bolivia.py
holidays/countries/bosnia_and_herzegovina.py
holidays/countries/botswana.py
holidays/countries/brazil.py
holidays/countries/brunei.py
holidays/countries/bulgaria.py
holidays/countries/burkina_faso.py
holidays/countries/burundi.py

This PR continues #1368. Update countries starting w/ b.

Use HolidayBase::_add_holiday_* family methods [b]

---

holidays/countries/cambodia.py
holidays/countries/cameroon.py
holidays/countries/canada.py
holidays/countries/chad.py
holidays/countries/chile.py
holidays/countries/china.py
holidays/countries/colombia.py
holidays/countries/costa_rica.py
holidays/countries/croatia.py
holidays/countries/cuba.py
holidays/countries/curacao.py
holidays/countries/cyprus.py
holidays/countries/czechia.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ c.

Use HolidayBase::_add_holiday_* family methods [c]

---

holidays/countries/djibouti.py
holidays/countries/dominican_republic.py
holidays/countries/ecuador.py
holidays/countries/egypt.py
holidays/countries/el_salvador.py
holidays/countries/estonia.py
holidays/countries/eswatini.py
holidays/countries/ethiopia.py
holidays/countries/finland.py
holidays/countries/france.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ d-f.

Use HolidayBase::_add_holiday_* family methods [d-f]

---

holidays/countries/gabon.py
holidays/countries/georgia.py
holidays/countries/germany.py
holidays/countries/greece.py
holidays/countries/guatemala.py
holidays/countries/honduras.py
holidays/countries/hongkong.py
holidays/countries/hungary.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ g-h.

Use HolidayBase::_add_holiday_* family methods [g-h]

---

README.rst
holidays/countries/georgia.py
holidays/locale/en_US/LC_MESSAGES/GE.po
holidays/locale/uk/LC_MESSAGES/GE.po
tests/countries/test_georgia.py

Update Georgia holidays, add uk localization.

Update Georgia holidays, add uk localization

---

README.rst
holidays/countries/greece.py
holidays/locale/el/LC_MESSAGES/GR.po
holidays/locale/uk/LC_MESSAGES/GR.po
tests/countries/test_greece.py

Update Greece holidays:
- add uk localization
- add half-day holidays

Update Greece holidays: add uk localization

---

holidays/countries/iceland.py
holidays/countries/india.py
holidays/countries/indonesia.py
holidays/countries/ireland.py
holidays/countries/isle_of_man.py
holidays/countries/italy.py
holidays/countries/jamaica.py
holidays/countries/japan.py
holidays/countries/kazakhstan.py
holidays/countries/kenya.py
holidays/countries/kyrgyzstan.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ i-k.

Use HolidayBase::_add_holiday_* family methods [i-k]

---

holidays/countries/latvia.py
holidays/countries/lesotho.py
holidays/countries/lithuania.py
holidays/countries/luxembourg.py
holidays/countries/madagascar.py
holidays/countries/malawi.py
holidays/countries/malaysia.py
holidays/countries/malta.py
holidays/countries/marshall_islands.py
holidays/countries/mexico.py
holidays/countries/moldova.py
holidays/countries/monaco.py
holidays/countries/montenegro.py
holidays/countries/morocco.py
holidays/countries/mozambique.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ l-m.

Use HolidayBase::_add_holiday_* family methods [l-m]

---

holidays/countries/romania.py
holidays/countries/russia.py
holidays/countries/san_marino.py
holidays/countries/saudi_arabia.py
holidays/countries/serbia.py
holidays/countries/singapore.py
holidays/countries/slovakia.py
holidays/countries/slovenia.py
holidays/countries/south_africa.py
holidays/countries/south_korea.py
holidays/countries/spain.py
holidays/countries/sweden.py
holidays/countries/switzerland.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ q-s.

Use HolidayBase::_add_holiday_* family methods [q-s]

---

holidays/countries/taiwan.py
holidays/countries/thailand.py
holidays/countries/tunisia.py
holidays/countries/turkey.py
holidays/countries/ukraine.py
holidays/countries/united_arab_emirates.py
holidays/countries/united_kingdom.py
holidays/countries/united_states.py
holidays/countries/uruguay.py
holidays/countries/uzbekistan.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ t-u.

Use HolidayBase::_add_holiday_* family methods [t-u]

---

holidays/countries/vatican_city.py
holidays/countries/venezuela.py
holidays/countries/vietnam.py
holidays/countries/zambia.py
holidays/countries/zimbabwe.py

This PR continues https://github.com/vacanza/python-holidays/pull/1368. Update countries starting w/ v-z.

Use HolidayBase::_add_holiday_* family methods [v-z]

---

.pre-commit-config.yaml
holidays/helpers.py
holidays/holiday_base.py
tests/common.py

Resolves #1408.
Update flake8 version. Fix E721 warnings.

Bump flake8 version from 6.0.0 to 6.1.0

---

holidays/countries/austria.py
holidays/holiday_base.py
tests/countries/test_austria.py

Fixes #1404 
Automatically convert subdivision code from int to str. Apply convertion to deprecated subdiv params (prov, state) too.

Automatically convert subdivision code from int to str

---

holidays/countries/saudi_arabia.py
holidays/locale/ar/LC_MESSAGES/SA.po
holidays/locale/en_US/LC_MESSAGES/SA.po
tests/countries/test_saudi_arabia.py

Update Saudi Arabia:
- fix observed holidays for Eid al-Fitr and Eid al-Adha.

Update Saudi Arabia holidays: fix Eid al-Fitr and Eid al-Adha observance

---

holidays/countries/singapore.py
tests/countries/test_singapore.py

Added Singapore Polling Day holiday on 1 September 2023, as Announced in state-associated press on 12 August 2023: https://www.straitstimes.com/singapore/politics/singapore-presidential-election-2023-polling-day-on-sept-1-nomination-day-on-aug-22.

Update Singapore holidays: add 2023 Polling Day

---

.pre-commit-config.yaml

Bump mypy version from 1.5.0 to 1.5.1

Bump mypy version from 1.5.0 to 1.5.1

---

docs/source/examples.rst

Resolves #1434 
Update documentation: correct inheritance example

Update documentation: correct inheritance example

---

holidays/countries/bosnia_and_herzegovina.py
holidays/countries/latvia.py

Fix months imports (from `holidays.calendars.gregorian` instead of `holidays.constants`).

Fix months imports

---

holidays/holiday_base.py
tests/test_holiday_base.py
tests/test_l10n.py
tests/test_utils.py

Update HolidayBase tests
- Group tests by category
- Use stubs instead of real entity objects
- Use type specific asserts
- Add `HolidayBase::__bool__()` tests

Update HolidayBase tests

---

tests/common.py
tests/test_registry.py
tests/test_utils.py

Update skipIf rules for heavy tests

Update skipIf rules for heavy tests

---

.github/workflows/ci-cd.yml

I'm going to experiment w/ the merge queue feature. This PR adds the required merge queue trigger.

Add merge queue support

---

README.rst
holidays/constants.py
holidays/countries/canada.py
holidays/locale/ar/LC_MESSAGES/CA.po
holidays/locale/en/LC_MESSAGES/CA.po
holidays/locale/fr/LC_MESSAGES/CA.po
holidays/locale/th/LC_MESSAGES/CA.po
tests/countries/test_canada.py

Massive update of Canadian holidays:
- separation of holiday categories (PUBLIC - nationwide statutory holidays, GOVERNMENT - federal statutory holidays, OPTIONAL - observed by many employers across the country), added optional holidays of provinces and territories.
- remove Ontario as default province
- full tests update

Update Canada holidays

---

holidays/countries/united_kingdom.py
tests/countries/test_united_kingdom.py

Update United Kingdom holidays:
- NIR: add observed holiday to "Battle of the Boyne"
- SCT: add observed holiday to "St. Andrew's Day"
- SCT: fix New Year holidays observed rule

Update United Kingdom holidays

---

.github/workflows/pre-commit-autoupdate.yml

Update pre commit autoumatic update workflow:
- Add token contents/pull-requests write permissions
- Run job for main repository only
- Set `delete-branch` flag to `true`

Update pre commit automatic update workflow

---

holidays/countries/liechtenstein.py
tests/countries/test_liechtenstein.py

Update Liechtenstein holidays: specify bank holidays.

Update Liechtenstein holidays: specify bank holidays

---

MANIFEST.in

Resolves #1497 
Explicitly add py.typed

Add py.typed to MANIFEST.in includes

---

pyproject.toml

Long overdue maintainers list update (as we've migrated to pyproject.toml)

Update project metadata: add @KJhellico to maintainers

---

.github/workflows/pre-commit-autoupdate.yml

Run auto-update jobs for source repository only. Fix code style.

Update pre-commit hooks automatic update workflow

---

.github/workflows/ci-cd.yml
README.rst

Use OIDC (trusted publishers) for PyPI uploads. This approach provides publishing ability with no stored permanent tokens.
Additional changes:
- Reformat configuration file
- Add pypy-3.9, pypy-3.10 to test matrix

Use OIDC (trusted publishers) for PyPI uploads

---

pyproject.toml

Set pyproject.toml project version dynamically

Set pyproject.toml project version dynamically

---

holidays/holiday_base.py

Remove redundant gettext assignment

Remove redundant gettext assignment

---

README.rst
holidays/countries/portugal.py
tests/countries/test_portugal.py

Update Portugal holidays: add holiday categories (moved optional holidays from "Ext" subdivision to separate category).

Update Portugal holidays: add holiday categories

---

holidays/countries/australia.py
holidays/countries/new_zealand.py
holidays/groups/international.py

- Refactor some Australia holidays
- Add Anzac Day to `InternationalHolidays`

Refactor Australia holidays

---

holidays/countries/isle_of_man.py
tests/countries/test_isle_of_man.py

Refactor Tynwald Day calculation.

Refactor Isle of Man holidays (Tynwald Day)

---

.github/workflows/ci-cd.yml

Avoid running stale code tests.

Set concurrency group for CI/CD jobs

---

docs/source/examples.rst
holidays/helpers.py
holidays/holiday_base.py
tests/countries/test_austria.py
tests/countries/test_belgium.py
tests/countries/test_brazil.py
tests/countries/test_bulgaria.py
tests/countries/test_canada.py
tests/countries/test_china.py
tests/countries/test_greece.py
tests/countries/test_indonesia.py
tests/countries/test_japan.py
tests/countries/test_laos.py
tests/countries/test_liechtenstein.py
tests/countries/test_portugal.py
tests/countries/test_slovakia.py
tests/countries/test_south_korea.py
tests/countries/test_tanzania.py
tests/countries/test_thailand.py
tests/countries/test_timor_leste.py
tests/countries/test_uruguay.py
tests/test_holiday_base.py

Extend HolidayBase::category to accept a single value
- Introduce helpers::_normalize_arguments handler
- Update tests
- Update examples documentation

Extend HolidayBase::categories to accept a single value

---

holidays/countries/slovakia.py
holidays/locale/en_US/LC_MESSAGES/SK.po
holidays/locale/sk/LC_MESSAGES/SK.po
holidays/locale/uk/LC_MESSAGES/SK.po
tests/countries/test_slovakia.py

Fix missing space and improve spelling.

Update Slovakia holidays

---

holidays/financial/ny_stock_exchange.py

Migrate NYSE holidays to `ObservedHolidayBase`.

Migrate NYSE holidays to ObservedHolidayBase

---

.gitignore
holidays/locale/pot/UA.pot
scripts/l10n/generate_po_files.py

Prepare project for Weblate integration [UA]
I need to whitelist at least one .pot file to setup a test Weblate project and further play with the integration.

Prepare project for Weblate integration [UA]

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.rst

Update PR template and contributing guidelines

Update PR template and contributing guidelines

---

holidays/countries/netherlands.py
tests/countries/test_netherlands.py

Update Netherlands holidays: fix Liberation Day.
Closes #1590.

Update Netherlands holidays: fix Liberation Day

---

Makefile

Regenerate .mo files before snapshots creation.

Update Makefile: fix snapshot generation process

---

holidays/countries/kazakhstan.py

Fix escaping and lint inhibition

---

README.rst

Make sure the shields look consistently.

Update README: fix shields style

---

holidays/calendars/thai.py

Refactor Thai calendar (some optimization).

Refactor Thai calendar

---

holidays/locale/uk/LC_MESSAGES/AZ.po
holidays/locale/uk/LC_MESSAGES/ID.po
holidays/locale/uk/LC_MESSAGES/TR.po
holidays/locale/uk/LC_MESSAGES/UZ.po

Update estimated label uk l10n

Update estimated label uk l10n

---

holidays/countries/thailand.py
snapshots/countries/TH_COMMON.json
tests/countries/test_thailand.py

The Thai government announced a new `Bridge Public Holiday` for the Songkran festival on 12th April 2024.
https://www.thaipbs.or.th/news/content/336973

Update Thailand holidays: add Bridge Public Holiday on Apr 12, 2024

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/pre-commit-autoupdate.yml
CONTRIBUTING.rst
README.rst
RELEASE.rst
scripts/generate_release_notes.py

Resolves #1695 
This PR reflects changes related to the recent branch renaming:
- master -> main
- beta -> dev

Rename repository branches

---

tests/countries/test_united_states.py

Update test coverage to 100%

---

tests/test_docs.py

Another attempt to play with regex to avoid Sonar warnings. The reports says it's fine (again!).

Fix SonarCloud security hotspots (attempt #2)

---

tests/test_docs.py

Another attempt to fix SonarCloud security hotspots (1 left).

Fix SonarCloud security hotspots (attempt #3)

---

Makefile

Update Makefile clean action

---

.github/workflows/ci-cd.yml

Add tests for built package, for freshly built package functionality check (#1479).

Add package build tests

---

holidays/countries/bangladesh.py
holidays/countries/bolivia.py
holidays/countries/bosnia_and_herzegovina.py
holidays/countries/italy.py
holidays/countries/kuwait.py
holidays/countries/liechtenstein.py
holidays/countries/seychelles.py
tests/__init__.py
tests/calendars/__init__.py
tests/countries/__init__.py
tests/countries/test_bolivia.py
tests/countries/test_bosnia_and_herzegovina.py
tests/countries/test_kuwait.py
tests/countries/test_liechtenstein.py
tests/countries/test_seychelles.py
tests/financial/__init__.py

All .py files header unification.

Unify file headers after recent update

---

holidays/countries/south_africa.py
tests/countries/test_south_africa.py

Update South Africa holidays: add public holiday on May 29, 2024 (election day).

Update South Africa holidays: add public holiday on May 29, 2024

---

CONTRIBUTING.rst

Add `Contributors` paragraph to `CONTRIBUTING.rst`

Update contributing guidelines

---

README.rst

Update badges in README:
- replace code style with `ruff`
- update color format in hyperlinks

Update badges in README

---

holidays/countries/laos.py

Refactor Laos holidays (Year-End Bank Holiday).

Refactor Laos holidays

---

holidays/countries/japan.py

Migrate Japan holidays to `ObservedHolidayBase`.

Migrate Japan holidays to ObservedHolidayBase

---

pyproject.toml

Narrow down ignored warnings

---

README.rst
holidays/countries/aruba.py
holidays/countries/curacao.py
holidays/locale/pap_AW/LC_MESSAGES/AW.po
holidays/locale/pap_CW/LC_MESSAGES/CW.po

Actually, Aruba and Curaçao use different [dialects of papiamento](https://en.wikipedia.org/wiki/Papiamento#Distribution_and_dialects), each with its own orthography. Therefore, it's logical to use separate locales for them.

Update Aruba and Curaçao holidays l10n (split locales)

---

.github/workflows/ci-cd.yml

- Group PR and related commits CI/CD jobs
- Update merge queue to trigger CI/CD for dev/main/v1 only

Tune up CI/CD jobs concurrency

---

.github/workflows/ci-cd.yml

Update CI/CD: don't cancel concurrent jobs for dev/main/v1

Update CI/CD: don't cancel concurrent jobs for dev/main/v1

---

README.rst

Update coverage badge

---

holidays/deprecation.py

Add SemVer link based on https://github.com/vacanza/python-holidays/discussions/1800#discussioncomment-9884280

Update v1 incompatibility warning

---

.github/workflows/ci-cd.yml

Don't run tests on Github readonly queue push events

Don't run tests on Github readonly queue push events

---

.github/workflows/ci-cd.yml
requirements/tests.txt
tests/third_party/test_numpy.py
tox.ini

Originally the PR was `Update test matrix: remove pypy`. After a talk w/ @KJhellico we agreed to remove it from the package metadata too. Removing this code simplifies maintenance process a lot.
All pypy related issues (not sure if we've ever seen one) will still be handled as any other bug fix requests -- on individual basis.

Drop PyPy support

---

tests/countries/test_malawi.py

Fix N804 for `TestMalawi::setUpClass()`

Fix Malawi tests

---

requirements/docs.txt

Update docs requirements: revert sphinx to v7.4.7

Update docs requirements: revert sphinx to v7.4.7

---

.github/workflows/pre-commit-autoupdate.yml

Replace `pre-commit-autoupdate-action` with local commands. Use pre-commit cache during environment setup.

Update pre-commit automatic update

---

.github/workflows/ci-cd.yml

Update Github release upload process

Update Github release upload process

---

.github/workflows/pre-commit-autoupdate.yml

Bump actions/cache from v3 to v4

Bump actions/cache from v3 to v4

---

.pre-commit-config.yaml
pyproject.toml

Update pre-commit: add bandit

---

.github/workflows/ci-cd.yml

Simplify GitHub release upload command

Update CI/CD: simplify gh release upload

---

.github/workflows/ci-cd.yml

Update SBOM artifact path

---

.github/workflows/update-snapshots.yml

Implement automatic snapshots updates

Add automatic snapshots update workflow

---

.github/labeler.yml
.github/workflows/prl-labeler.yml

Add PR labeler

---

holidays/countries/south_korea.py
snapshots/countries/KR_COMMON.json
tests/countries/test_south_korea.py

Update South Korea holidays: add public holiday on October 1, 2024 as Armed Forces Day.
Closes #1972.

Update South Korea holidays: add Armed Forces Day in 2024

---

holidays/calendars/thai.py
holidays/holiday_base.py

Fix some docstrings (in `HolidayBase::pop_named` and `_ThaiLunisolar`).

Fix some docstrings

---

.github/labeler.yml

Update `ci` label configuration

Update `ci` label configuration

---

holidays/groups/__init__.py
holidays/groups/buddhist.py
holidays/groups/chinese.py
holidays/groups/eastern.py
holidays/groups/hindu.py
holidays/groups/islamic.py

Add `EasternCalendarHolidays` to holidays groups (optimize commonly used code).

Add `EasternCalendarHolidays` to holidays groups

---

pyproject.toml
tests/test_package.py

Update `holidays` package metadata

Update `holidays` package metadata

---

tests/countries/test_canada.py

Refactor Canada tests

---

tests/countries/test_united_states.py

Refactor United States tests

---

holidays/countries/finland.py
holidays/countries/luxembourg.py
holidays/countries/moldova.py
holidays/groups/international.py

Add Europe Day (May 9) to InternationalHolidays

Add Europe Day to InternationalHolidays

---

README.rst
holidays/countries/portugal.py

Adds alias to each of the subdivisions (districts) in accordance with ISO 3166-2:PT

Add Portugal subdivision aliases

---

pyproject.toml

Update ruff configuration: add [Pylint errors](https://docs.astral.sh/ruff/rules/#error-e_1) check, to avoid [such issues](https://github.com/vacanza/holidays/pull/2108#discussion_r1829950969).

Update ruff configuration: add Pylint errors check

---

holidays/holiday_base.py
holidays/observed_holiday_base.py
holidays/utils.py
scripts/generate_snapshots.py
tests/common.py
tests/countries/test_canada.py
tests/countries/test_germany.py
tests/countries/test_switzerland.py

This check is a more idiomatic and performant. The PR contains some other related changes as well.

Refactor some `if len(container)...` cases to `if container...`

---

holidays/helpers.py
tests/common.py
tests/test_helpers.py

Update helpers::_normalize_arguments, add helpers tests

Update helpers::_normalize_arguments, add helpers tests

---

.github/workflows/ci-cd.yml

Bump codecov/codecov-action to v5.

Bump codecov/codecov-action to v5

---

pyproject.toml
tests/test_package.py

Update PyPI package description

Update pyproject.toml: clarify project summary

---

.github/workflows/ci-cd.yml

I'm trying to find a way to trigger CI/CD automatically upon pre-commit auto-updater job completion.

Update CI/CD trigger section

---

.github/workflows/ci-cd.yml

Update "Set up Python" to use 3.13

Update "Set up Python" to use 3.13

---

.github/workflows/ci-cd.yml

Update CI/CD pipeline to sign release artifacts using Sigstore.

Sign release artifacts using Sigstore

---

holidays/financial/ny_stock_exchange.py
snapshots/financial/XNYS.json
tests/financial/test_ny_stock_exchange.py

Add new holiday for US markets.  1/9/2025: Day of Mourning for President Jimmy Carter.
https://apnews.com/article/stock-exchange-closes-jan-9-carter-death-32fe7dcc8546ed98d2408abf8f498b08

Update XNYS: add a Day of Mourning for President Jimmy Carter

---

holidays/countries/afghanistan.py
holidays/countries/iran.py

According to [wikipedia](https://en.wikipedia.org/wiki/Workweek_and_weekend#Table), Afghanistan's and Iran's workweek is from Sunday to Thursday and Saturday to Thursday, do according changes.
Closed previous PR #2222 which updated Afghanistan only.

Update Afghanistan and Iran holidays: change weekend to FRI-SAT and FRI respectively

---

scripts/generate_release_notes.py

Update PR exclusion logic

---

holidays/countries/slovakia.py
tests/countries/test_slovakia.py

Update Slovakia holidays: Constitution Day is working day since 2024.

Update Slovakia holidays: Constitution Day is working day since 2024

---

MANIFEST.in

Remove .po files from distribution bundles (sdist and bdist).

Remove .po files from distribution bundles

---

.github/workflows/ci-cd.yml
.github/workflows/pre-commit-autoupdate.yml
.github/workflows/prl-labeler.yml
.github/workflows/update-snapshots.yml

Pin CI/CD Ubuntu version

---

holidays/countries/thailand.py

As แรกนาขวัญ (Royal Ploughing Ceremony) entries are all manually assigned, `MAY, 13` fallback date is no longer needed.

Update Thailand holidays: refactor Royal Ploughing Ceremony code

---

.github/workflows/update-snapshots.yml

Update automatic snapshots update workflow.

Update automatic snapshots update workflow

---

make.cmd
scripts/generate_snapshots.py
scripts/l10n/generate_po_files.py

Update internal scripts (.PO files and snapshots generators): force LF as line separator. This will prevent unnecessary changes to files on Windows (due to replacing the delimiter with the default CRLF).

Update internal scripts

---

README.rst

Update README with recently obtained DOI 🤷‍♂️ 

Update README: add DOI

---

holidays/holiday_base.py
pyproject.toml
tests/test_holiday_base.py
tests/test_registry.py

Add Python syntax check with ruff-pyupgrade rules ([UP](https://docs.astral.sh/ruff/rules/#pyupgrade-up)).

Add Python syntax check with ruff-pyupgrade rules

---

README.rst

Update Zenodo record URL in README.
I think it would be better for us to add a [new version](https://help.zenodo.org/docs/deposit/manage-versions/) to the existing Zenodo record when we release new Holidays version. So we'll have a permanent URL (directed to latest version).
This needs to be considered when working on #2305.

Update Zenodo record URL in README

---

scripts/l10n/generate_mo_files.py
scripts/l10n/generate_po_files.py

Update l10n scripts:
- remove all .mo files before generation
- add "Language" and "X-Source-Language" entries to .pot files metadata

Update l10n scripts

---

.coderabbit.yaml

Add .coderabbit.yaml

---

holidays/holiday_base.py
tests/test_holiday_base.py

Introduce `HolidayBase::__getstate__` and `HolidayBase::__setstate__` methods for proper serialization of holidays objects.
Resolve #1236.

Introduce HolidayBase methods for proper serialization

---

holidays/holiday_base.py

Fix l10n handling

---

pyproject.toml
tests/test_package.py

Update pyproject.toml: align with PEP 639 metadata format.
[PEP 639](https://peps.python.org/pep-0639/) has changed the way the `license` field is [declared](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license).

Update pyproject.toml: align with PEP 639 metadata format

---

scripts/generate_release_notes.py

Update release notes generator: adjust to CHANGES.md format.

Update release notes generator

---

requirements/tests.txt
tests/test_package.py

Update tests requirements (limit `importlib-metadata` dependency to Python versions < 3.10)

Update tests requirements

---

holidays/calendars/thai.py
holidays/groups/thai.py

- Cleanups earlier references that no longer applies to the current `_ThaiLunisolar` implementation.
- Upgrades all syntax to modern library standard as of patch v0.70.
- Fixes other grammatical errors.

Update `_ThaiLunisolar` and `ThaiCalendarHolidays` documentation

---

holidays/locale/be/LC_MESSAGES/BY.po
holidays/locale/en_US/LC_MESSAGES/BY.po
holidays/locale/ru/LC_MESSAGES/BY.po
holidays/locale/th/LC_MESSAGES/BY.po

Automatically reformat BY.po files.
I know @KJhellico re-formatted them [recently](https://github.com/vacanza/holidays/commit/d0eaf75c889074beeaff28802c019563c526564d). So it could be OS/env related

Update BY.po files

---

holidays/countries/pakistan.py
holidays/locale/en_PK/LC_MESSAGES/PK.po
holidays/locale/en_US/LC_MESSAGES/PK.po
holidays/locale/ur_PK/LC_MESSAGES/PK.po
tests/countries/test_pakistan.py

Added the Pakistan holiday Youm-e-Takbeer and missing holidays for 2025.
Source:
https://en.wikipedia.org/wiki/Public_holidays_in_Pakistan
https://ur.wikipedia.org/wiki/%D8%AA%D8%B9%D8%B7%DB%8C%D9%84%D8%A7%D8%AA_%D9%BE%D8%A7%DA%A9%D8%B3%D8%AA%D8%A7%D9%86

Update Pakistan holidays: add Youm-e-Takbeer holiday

---

.pre-commit-config.yaml
holidays/countries/malaysia.py
holidays/countries/taiwan.py
holidays/holiday_base.py
holidays/observed_holiday_base.py
pyproject.toml

Update mypy configuration

---

tests/common.py

Update Python latest supported version format

Update Python latest supported version format

---

requirements/dev.txt
scripts/l10n/generate_po_files.py

Update .po files generator (support .po files without msgids).

Update .po files generator

---

.pre-commit-config.yaml
AUTHORS.md
tests/test_docs.py

Update documentation tests: add AUTHORS.md checking (header and names order)

Update documentation tests: add AUTHORS.md checking

---

tests/countries/test_taiwan.py

This cleanups Taiwan's test case, in line with @KJhellico's suggestion in #2489 and the existing [`test_israel.py`](https://github.com/vacanza/holidays/blob/ce30a785023835e2f2e37d65944cc5aef0b64eec/tests/countries/test_israel.py#L25) ones.
(I've double-checked for other similar instances, but Taiwan implementation is the only one affected by this)

Update Taiwan holidays: test case refactor

---

README.md

Update README: add Snyk package health badge.

Update README: add Snyk package health badge

---

holidays/countries/cambodia.py
holidays/countries/thailand.py
holidays/groups/thai.py
holidays/locale/en_US/LC_MESSAGES/KH.po
holidays/locale/km/LC_MESSAGES/KH.po
holidays/locale/th/LC_MESSAGES/KH.po

- Cleanups incorrect docstring description for Makha Bucha's holiday group assignment.
- Ensures Cambodia's holiday entries code comment ends with a dot ( . ).
- Sorts Thailand's holidays attributes assignment.
Doesn't otherwise affects holiday list in these countries.

Docstring cleanup for Indochinese countries

---

holidays/__init__.py

Disable v1 incompatibility warning.

Disable v1 incompatibility warning

---

holidays/countries/albania.py
holidays/countries/canada.py
holidays/countries/hongkong.py
holidays/countries/ivory_coast.py
holidays/countries/macau.py
holidays/countries/portugal.py
holidays/ical.py
holidays/locale/en_CI/LC_MESSAGES/CI.po
holidays/locale/en_US/LC_MESSAGES/CI.po
holidays/locale/fr/LC_MESSAGES/CI.po
tests/countries/test_ivory_coast.py

Fix typography: replace U+2019 with "'" and U+2013 with '-'.

Fix typography: replace U+2019 with "'" and U+2013 with '-'

---

scripts/docs/gen_changelog.py

Make clickable links to PR on GitHub in changelog (from #nnnn references).
It looks like [this](https://holidays--2540.org.readthedocs.build/en/2540/changelog/).

Update documentation build: make PR links in changelog

---

.pre-commit-config.yaml
holidays/countries/malaysia.py
pyproject.toml

Update pre-commit config:
- replace `bandit` hook with [flake8-bandit](https://docs.astral.sh/ruff/rules/#flake8-bandit-s)
- remove excessive `mypy` additional dependencies

Update pre-commit config

---

.pre-commit-config.yaml
SPONSORSHIP.md

Improve FAQ look at GitHub:
Before:
After:

Update sponsorship FAQ formatting

---

.github/workflows/ci-cd.yml
.github/workflows/pre-commit-autoupdate.yml
.github/workflows/update-snapshots.yml
.readthedocs.yaml
tox.ini

Set Python 3.13 as primary in CI/CD.

Set Python 3.13 as primary in CI/CD

---

holidays/countries/philippines.py

Adding recent proclamation url for Eid'l Adha. 

Update Philippines holidays: 2025 Eid'l Adha Proclamation URL

---

holidays/countries/french_southern_territories.py
tests/countries/test_french_southern_territories.py

Refactor TF holidays, extend tests.

Refactor TF holidays

---

holidays/countries/trinidad_and_tobago.py

Remove the unnecessary `dts_observed.add( ... )` assignments for Good Friday and Easter Monday as discovered during a code review discussion with @Roshan-1024 for #2609 .

Refactor Trinidad and Tobago holidays

---

requirements/tests.txt
tests/third_party/test_numpy.py

Bump numpy to 2.3.0 (for Python 3.11+).

Bump numpy to 2.3.0

---

pyproject.toml

Add `testpaths` option to speed up tests collection.

Update pytest configuration

---

tests/test_ical.py

Fix iCal exporter tests ([1](https://github.com/vacanza/holidays/actions/runs/15959376565/job/45010480249#step:5:95), [2](https://github.com/vacanza/holidays/actions/runs/15963020968/job/45018482348#step:5:89)).
Libya PR branch - [fail](https://github.com/KJhellico/python-holidays/actions/runs/15971206960),
Libya PR branch + this fix - [success](https://github.com/KJhellico/python-holidays/actions/runs/15971272655).

Fix iCal exporter tests

---

holidays/groups/hebrew.py
tests/countries/test_australia.py
tests/countries/test_malaysia.py
tests/countries/test_spain.py
tests/countries/test_switzerland.py

Improve some variable naming

---

docs/examples.md

Added some documentation for this pattern. Any feedback is welcome!
Closes #1666

Document `_add_holiday_*` pattern
